### ISSUE TITLE
issue with links in the repo

### ISSUE THREAD

**Issue by papasanimohansrinivas** [AILab-CVC/YOLO-World#1]
@StevenGrove @wondervictor  links   for huggingface space and models weights are not working and pointed to repo itself

**Comment by wondervictor** [comment]
@papasanimohansrinivas thanks for your interest, we will upload the code, models, and HuggingFace demo in a day, please stay tuned☕️!

**Comment by wondervictor** [comment]
Hi all, we have released the code and models! Thanks for your interest in YOLO-World, again! You can try the demo on HuggingFace now!
