### ISSUE TITLE
有个问题想请教。

### ISSUE THREAD

**Issue by QzYER** [AILab-CVC/YOLO-World#10]
groundingdino的推理是同同时需要对文本和图像 编码，是同时进行的，因为要用到交叉注意力的计算。而yolo-world是离线方式的，但是不是很明白论文中的离线方式是什么？我的理解是：不用同时对文本和图像处理，在推理过程中，文本和图像不是同时进行的。我可以这么理解吗？

**Comment by wondervictor** [comment]
@QzYER 您好，非常感谢对YOLO-World的关注，这里的离线方式其实是对我们自己定义的vocabulary提前计算好相应的Text Embeddings(Grounding/Referring目前还需要同时计算)，然后作为参数加入到模型去，这种方式可以大大降低infer时候文本的计算。

**Comment by QzYER** [comment]
谢谢你的回复。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AILab-CVC/YOLO-World"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月2日(星期五) 上午10:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AILab-CVC/YOLO-World] 有个问题想请教。 (Issue #10)





 
@QzYER 您好，非常感谢对YOLO-World的关注，这里的离线方式其实是对我们自己定义的vocabulary提前计算好相应的Text Embeddings(Grounding/Referring目前还需要同时计算)，然后作为参数加入到模型去，这种方式可以大大降低infer时候文本的计算。
