### ISSUE TITLE
Image_demo.py question

### ISSUE THREAD

**Issue by Graysonggg** [AILab-CVC/YOLO-World#101]
Good work. 
I have a problem that how should I define the following two classes in image_demo.py Line 18-19?

BOUNDING_BOX_ANNOTATOR = None  # Define BOUNDING_BOX_ANNOTATOR object
LABEL_ANNOTATOR = None  # Define LABEL_ANNOTATOR object

**Comment by HGao-cv** [comment]
> Good work. I have a problem that how should I define the following two classes in image_demo.py Line 18-19?
> 
> BOUNDING_BOX_ANNOTATOR = None # Define BOUNDING_BOX_ANNOTATOR object LABEL_ANNOTATOR = None # Define LABEL_ANNOTATOR object
You can try these three modifications:

1. (probably on the 15  line）
# Removed unnecessary import
import supervision as sv
2. （probably on the 20 line）
# BOUNDING_BOX_ANNOTATOR = None  # Define BOUNDING_BOX_ANNOTATOR object
# LABEL_ANNOTATOR = None  # Define LABEL_ANNOTATOR object
BOUNDING_BOX_ANNOTATOR = sv.BoxAnnotator()
LABEL_ANNOTATOR = sv.LabelAnnotator(text_position=sv.Position.CENTER)

3. （probably on  the 94 line）
    detections = sv.Detections(
        xyxy=pred_instances['bboxes'],
        class_id=pred_instances['labels'],
        confidence=pred_instances['scores']
    )

**Comment by Graysonggg** [comment]
Thank you for your soon reply.
