### ISSUE TITLE
Could YOLO-World use some images as category?

### ISSUE THREAD

**Issue by ruaqy** [AILab-CVC/YOLO-World#102]
Some texts are ambiguous for discription of object. 
For example, if I want to find out Lays chips, it's hard to find a word to descibe it.
If YOLO-Wolrd could use CLIP-like embedder to embed vector from image, it will be relaxed to work.

**Comment by wondervictor** [comment]
Hi @ruaqy, sure! We are now working on the image prompts.

**Comment by okideal** [comment]
would it work that use image encoder part of clip instead of the text encoder

**Comment by wondervictor** [comment]
@okideal Sure, it will work and we are doing it.

**Comment by okideal** [comment]
nice work and I'm looking forward to it.

btw could you pls provide a accuracy comparison between the implementation and the owlvit's image prompt approach after it's been implemented?

**Comment by wondervictor** [comment]
Sure, we will do it.

**Comment by wondervictor** [comment]
Hi @okideal and @ruaqy, YOLO-World now supports both image and text prompts along with prompt tuning. You can refer to [Prompt YOLO-World](https://github.com/AILab-CVC/YOLO-World/blob/master/docs/prompt_yolo_world.md).

**Comment by wondervictor** [comment]
Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
