### ISSUE TITLE
Core Dumped when running demo.py

### ISSUE THREAD

**Issue by Asianfleet** [AILab-CVC/YOLO-World#103]
command:
python demo.py configs/pretrain/yolo_world_v2_x_vlpan_bn_2e-3_100e_4x8gpus_obj365v1_goldg_train_lvis_minival.py weights/yolo_world_v2_x_obj365v1_goldg_cc3mlite_pretrain-8698fbfa.pth

when I clicked the submit botton ,I get the error:
Running on local URL:  http://0.0.0.0:8080

To create a public link, set `share=True` in `launch()`.
illegal instruction (core dumped)
with no extra error output.

system: ubuntu20.04 server
GPU:single A100 40G

**Comment by wondervictor** [comment]
Hi @Asianfleet, could you try the new `demo.py`? We have fixed the errors in the demo and ONNX export now is supported!

**Comment by Asianfleet** [comment]
@wondervictor oh，Thanks for your work！
