### ISSUE TITLE
What are the correct  path/to/config path/to/weights to replicate your online demo 

### ISSUE THREAD

**Issue by jasonschwartzman** [AILab-CVC/YOLO-World#104]
https://huggingface.co/spaces/stevengrove/YOLO-World

I successfully was able to download and setup the 2.0 version, but I want to be able to run like your 
demo @StevenGrove.   Please assist.   are the weights and config in your repo? 

usage: image_demo.py [-h] [--topk TOPK] [--threshold THRESHOLD]
                     [--device DEVICE] [--show] [--annotation] [--amp]
                     [--output-dir OUTPUT_DIR]
                     [--cfg-options CFG_OPTIONS [CFG_OPTIONS ...]]
                     config checkpoint image text
image_demo.py: error: the following arguments are required: config, checkpoint, image, text

Image and Text I get... But the checkpoint and config?   Where?   I want to replicate the demo

**Comment by wondervictor** [comment]
Hi @jasonschwartzman, the `demo.py` now has been updated and you can have a try!

**Comment by wondervictor** [comment]
This issue will be closed since there is no further update related to the main topic. Besides, the error has been fixed already. Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
