### ISSUE TITLE
Anybody runs deploy.py successfully and get onnx file?

### ISSUE THREAD

**Issue by pixiaopi2018** [AILab-CVC/YOLO-World#105]
I got the error:
`RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: InstanceData`

**Comment by QzYER** [comment]
this is my error  log ：
Switch model to deploy modality.
Process Process-2:
Traceback (most recent call last):
  File "/home/bowen/anaconda3/envs/yolo8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/bowen/anaconda3/envs/yolo8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bowen/anaconda3/envs/yolo8/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/bowen/anaconda3/envs/yolo8/lib/python3.8/site-packages/mmdeploy/apis/pytorch2onnx.py", line 64, in torch2onnx
    data, model_inputs = task_processor.create_input(
  File "/home/bowen/anaconda3/envs/yolo8/lib/python3.8/site-packages/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 217, in create_input
    data_ = test_pipeline(data_)
  File "/home/bowen/anaconda3/envs/yolo8/lib/python3.8/site-packages/mmcv/transforms/base.py", line 12, in __call__
    return self.transform(results)
  File "/home/bowen/anaconda3/envs/yolo8/lib/python3.8/site-packages/mmcv/transforms/wrappers.py", line 88, in transform
    results = t(results)  # type: ignore
  File "/media/bowen/6202c499-4f0a-4280-af7e-d2ab4b6c74dd/home/bowen/YOLO-World-master/./yolo_world/datasets/transformers/mm_transforms.py", line 114, in __call__
    assert 'texts' in results or hasattr(self, 'class_texts'), (
AssertionError: No texts found in results.
03/06 22:50:35 - mmengine - ERROR - /home/bowen/anaconda3/envs/yolo8/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.

**Comment by pixiaopi2018** [comment]
> this is my error log ： Switch model to deploy modality. Process Process-2: Traceback (most recent call last): File "/home/bowen/anaconda3/envs/yolo8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap self.run() File "/home/bowen/anaconda3/envs/yolo8/lib/python3.8/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs) File "/home/bowen/anaconda3/envs/yolo8/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in **call** ret = func(*args, **kwargs) File "/home/bowen/anaconda3/envs/yolo8/lib/python3.8/site-packages/mmdeploy/apis/pytorch2onnx.py", line 64, in torch2onnx data, model_inputs = task_processor.create_input( File "/home/bowen/anaconda3/envs/yolo8/lib/python3.8/site-packages/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 217, in create_input data_ = test_pipeline(data_) File "/home/bowen/anaconda3/envs/yolo8/lib/python3.8/site-packages/mmcv/transforms/base.py", line 12, in **call** return self.transform(results) File "/home/bowen/anaconda3/envs/yolo8/lib/python3.8/site-packages/mmcv/transforms/wrappers.py", line 88, in transform results = t(results) # type: ignore File "/media/bowen/6202c499-4f0a-4280-af7e-d2ab4b6c74dd/home/bowen/YOLO-World-master/./yolo_world/datasets/transformers/mm_transforms.py", line 114, in **call** assert 'texts' in results or hasattr(self, 'class_texts'), ( AssertionError: No texts found in results. 03/06 22:50:35 - mmengine - ERROR - /home/bowen/anaconda3/envs/yolo8/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.


I fix this.  In your test_pipeline, add 'text_path' for the LoadText:

test_pipeline = [
    *_base_.test_pipeline[:-1],
    dict(type='LoadText', **text_path='/your/own/class_texts.json'**),
    dict(type='mmdet.PackDetInputs',
         meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape',
                    'scale_factor', 'pad_param', 'texts'))
]

**Comment by QzYER** [comment]
> > this is my error log ： Switch model to deploy modality. Process Process-2: Traceback (most recent call last): File "/home/bowen/anaconda3/envs/yolo8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap self.run() File "/home/bowen/anaconda3/envs/yolo8/lib/python3.8/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs) File "/home/bowen/anaconda3/envs/yolo8/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in **call** ret = func(*args, **kwargs) File "/home/bowen/anaconda3/envs/yolo8/lib/python3.8/site-packages/mmdeploy/apis/pytorch2onnx.py", line 64, in torch2onnx data, model_inputs = task_processor.create_input( File "/home/bowen/anaconda3/envs/yolo8/lib/python3.8/site-packages/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 217, in create_input data_ = test_pipeline(data_) File "/home/bowen/anaconda3/envs/yolo8/lib/python3.8/site-packages/mmcv/transforms/base.py", line 12, in **call** return self.transform(results) File "/home/bowen/anaconda3/envs/yolo8/lib/python3.8/site-packages/mmcv/transforms/wrappers.py", line 88, in transform results = t(results) # type: ignore File "/media/bowen/6202c499-4f0a-4280-af7e-d2ab4b6c74dd/home/bowen/YOLO-World-master/./yolo_world/datasets/transformers/mm_transforms.py", line 114, in **call** assert 'texts' in results or hasattr(self, 'class_texts'), ( AssertionError: No texts found in results. 03/06 22:50:35 - mmengine - ERROR - /home/bowen/anaconda3/envs/yolo8/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py - pop_mp_output - 80 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.
> 
> I fix this. In your test_pipeline, add 'text_path' for the LoadText:
> 
> test_pipeline = [ *_base_.test_pipeline[:-1], dict(type='LoadText', **text_path='/your/own/class_texts.json'**), dict(type='mmdet.PackDetInputs', meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape', 'scale_factor', 'pad_param', 'texts')) ]

官方关于deploy的文档也没有说明一下。

**Comment by n9s8a** [comment]
> I got the error: `RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: InstanceData`

Hi, I have got same error. How did you solve it?

**Comment by taofuyu** [comment]
> > I got the error: `RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: InstanceData`
> 
> Hi, I have got same error. How did you solve it?

https://github.com/AILab-CVC/YOLO-World/issues/106#issuecomment-1982844200
