### ISSUE TITLE
目前最基本的检测都不准，快有什么意义！

### ISSUE THREAD

**Issue by shihuojian** [AILab-CVC/YOLO-World#112]
@onuralpszr @jradikk @StevenGrove @wondervictor @NatanBagrov @ 我说的有问题，请各位指教，既然开源了还不让说,，你们鹅厂一直都这么自以为是吗？
![屏幕截图 2024-03-11 095936](https://github.com/AILab-CVC/YOLO-World/assets/19809313/e5a7128d-1ab5-4d8f-a7cd-64ec1b565ff4)

**Comment by shihuojian** [comment]
我简直不敢相信你们连最基本的测试都没做过就拿出来

**Comment by shihuojian** [comment]
你们的口气真的非常非常自大，承认不足真的有那么难！

**Comment by shihuojian** [comment]
#108 你们的口气真的非常非常自大，承认不足有那么难！

**Comment by wondervictor** [comment]
我觉得你没有用对，你觉得呢？
其次，我们没有觉得我们自大，更没有觉得自己做的多好，如果你上来无理由喷，那我不好意思，你不尊重我，我也不会尊重你。你把原图发来？

**Comment by shihuojian** [comment]
> @shihuojian 其次，我们不 觉得我们自大，更不觉得自己做的多好，如果你上来无理由喷，那我不好意思，你不尊重我，我也不会尊重你。你把原图发来？

那些回复还不是自大~~~不是都觉得很牛逼。因为需求类似的项目我基本都试过，说句实话，目前你们的最不准
![微信图片_20240311095503](https://github.com/AILab-CVC/YOLO-World/assets/19809313/1ef6f4f7-5ad4-40b1-8cf3-5be9f3e18cb3)

**Comment by wondervictor** [comment]
<img width="955" alt="截屏2024-03-11 10 22 36" src="https://github.com/AILab-CVC/YOLO-World/assets/15026693/7d3a4767-b02d-4fe2-8335-6437ef9cf007">
@shihuojian 请好好看看，这是在线demo的结果，你自己不会用，就不要乱喷，好吗？对人最起码的尊重都没有，还这么敏感的说我们自大？

**Comment by shihuojian** [comment]
> <img alt="截屏2024-03-11 10 22 36" width="955" src="https://private-user-images.githubusercontent.com/15026693/311568675-7d3a4767-b02d-4fe2-8335-6437ef9cf007.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMjQxMjQsIm5iZiI6MTcxMDEyMzgyNCwicGF0aCI6Ii8xNTAyNjY5My8zMTE1Njg2NzUtN2QzYTQ3NjctYjAyZC00ZmUyLTgzMzUtNjQzN2VmOWNmMDA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDAyMjM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1MjE4NTNlNmYzZTQ5ZDgzNzBhYzI0ZTRjZjE1OGQ5ZmZlOTRlN2ZhNjk1M2U0MWI3NGNjODgxY2I2NmIyYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uGWWENAGqqGWE5rColsK2hZ_SKp73BLPgCzMUY2eHZQ"> @shihuojian请好好看看，这是在线演示的结果，你自己不会用，就不要乱喷，好吗？对人最起码的尊重都没有，还这么敏感的说我们自大？

手呢？

**Comment by wondervictor** [comment]
<img width="1886" alt="截屏2024-03-11 10 24 06" src="https://github.com/AILab-CVC/YOLO-World/assets/15026693/d6c2339f-a5b3-4c30-8f8e-5d17e7ec0abc">
要不要看完整？什么是自大？

**Comment by shihuojian** [comment]
> <img alt="截屏2024-03-11 10 24 06" width="1886" src="https://private-user-images.githubusercontent.com/15026693/311568826-d6c2339f-a5b3-4c30-8f8e-5d17e7ec0abc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMjQxNjAsIm5iZiI6MTcxMDEyMzg2MCwicGF0aCI6Ii8xNTAyNjY5My8zMTE1Njg4MjYtZDZjMjMzOWYtYTViMy00YzMwLThmOGUtNWQxN2U3ZWMwYWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDAyMjQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMzljYTdlMzExNGE5MjYxZjc1Mjg3NzNjNDE3NDI5YTVkNDEyMDEwYjg0MTY5NGQzMDI0YTNjZWRlNzhhOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CkLG9flQdVGQSRXrA8x39GIk8WHp3uDoiTyezwLC10o"> 要不要看完整？什么是自大？

演示地址发来？

**Comment by wondervictor** [comment]
请问我们回复的issue哪一条自大了？哪一条是我们不承认别的好以及自己没问题？

**Comment by wondervictor** [comment]
https://huggingface.co/spaces/stevengrove/YOLO-World

**Comment by wondervictor** [comment]
我说了，你不会用，用的有问题，我们可以交流，沟通，我看到我第一时间会去follow大家的问题，我最近很忙，我也会尽量去看大家的case，请问，我们怎么自大？

**Comment by wondervictor** [comment]
@shihuojian

**Comment by wondervictor** [comment]
@shihuojian 要不要其他case我也帮你测一下呢？

**Comment by shihuojian** [comment]
> @shihuojian

不好意思，你们有没有想过那个环节出了问题，为什么我的结果会那样，我在哪里看到的，比如以下：
https://huggingface.co/spaces/SkalskiP/YOLO-World
https://www.youtube.com/watch?v=X7gKBGVz4vs

**Comment by wondervictor** [comment]
你把你的输入text里面，默认增加一个空的类别 `""`，这的确是我们的问题，在其他issue里面讨论过了，`""`需要作为negative类别。

**Comment by shihuojian** [comment]
> 你把你的输入文本里面，默认增加一个空的类别`""`，这确实是我们的问题，在其他问题里面讨论过了，`""`需要作为负类别。

建议这个去掉吧~
![屏幕截图 2024-03-11 103441](https://github.com/AILab-CVC/YOLO-World/assets/19809313/77edec8b-2713-433c-9457-f6d2b2e8d088)

**Comment by wondervictor** [comment]
这个东西呢在优化，涉及到了预训练问题，不过不影响使用，你可以尝试增加  `" "` 或者 `""`，是能直接用你最开始调用的代码运行的。

**Comment by shihuojian** [comment]
> > 你把你的输入文本里面，默认增加一个空的类别`""`，这确实是我们的问题，在其他问题里面讨论过了，`""`需要作为负类别。
> 
> 建议这个去掉吧~ ![屏幕截图 2024-03-11 103441](https://private-user-images.githubusercontent.com/19809313/311570505-77edec8b-2713-433c-9457-f6d2b2e8d088.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMjQ5MDcsIm5iZiI6MTcxMDEyNDYwNywicGF0aCI6Ii8xOTgwOTMxMy8zMTE1NzA1MDUtNzdlZGVjOGItMjcxMy00MzNjLTk0NTctZjZkMmIyZThkMDg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDAyMzY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YTAxMmJjZjljZGE3MWFkYjNlYzg3OTY3NTIzMzYzOTAwNzhiMDM1NDI1MzAyYTQ3NTQ4ZjkxOTZjMTI2YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HJO6ItT17qypkSw4bJd8SE2AIMQWS1OszmcY-injw_E)

作为国人英文不是很好，所以第一次进去就是这个，测试完全不能用，然后看了视频，试了下一点也不准，不然我也不会说~，表示抱歉，希望你们文档详细些

**Comment by shihuojian** [comment]
> 这个东西呢在优化，涉及到了预训练问题，不过不影响使用，你可以尝试增加 `" "` 或者 `""`，是能直接用你最开始调用的代码运行的。

好的

**Comment by wondervictor** [comment]
我接受批评，我也接受大家的建议与负面评价，但我希望所有的评价都是基于事实，如果你觉得哪里不对或者不符合预期，我觉得可以向大家一样提出你的问题或者上传的你的样本，如果是我们自身模型的缺陷，我欣然接受，我也愿意去改进，如果是使用的问题，我相信我有空看到就会帮你去解决，也有社区的同伴帮你去解决。

**Comment by wondervictor** [comment]
目前这是一个发展中的项目，还有很多待完善和优化的。

**Comment by shihuojian** [comment]
> @shihuojian 我觉得你没有用对，你觉得呢？ 其次，我们没有觉得我们自大，更没有觉得自己做的多好，如果你上来无理由喷，那我不好意思，你不尊重我，我也不会尊重你。你把原图发来？



> 我接受批评，我也接受大家的建议与负面评价，但我希望所有的评价都是基于事实，如果你觉得哪里不对或者不符合预期，我觉得可以向大家一样提出你的问题或者上传的你的样本，如果是我们自身模型的缺陷，我欣然接受，我也愿意去改进，如果是使用的问题，我相信我有空看到就会帮你去解决，也有社区的同伴帮你去解决。

#108 里面你们回复会让我觉得你们很自大，感觉你们都觉得很了不起，我想提建议说原由，但是看了回复我只会很生气，懂吗？感觉你们都很理直气壮，不问缘由

**Comment by shihuojian** [comment]
> > @shihuojian 我觉得你没有用对，你觉得呢？ 其次，我们没有觉得我们自大，更没有觉得自己做的多好，如果你上来无理由喷，那我不好意思，你不尊重我，我也不会尊重你。你把原图发来？
> 
> > 我接受批评，我也接受大家的建议与负面评价，但我希望所有的评价都是基于事实，如果你觉得哪里不对或者不符合预期，我觉得可以向大家一样提出你的问题或者上传的你的样本，如果是我们自身模型的缺陷，我欣然接受，我也愿意去改进，如果是使用的问题，我相信我有空看到就会帮你去解决，也有社区的同伴帮你去解决。
> 
> #108 里面你们回复会让我觉得你们很自大，感觉你们都觉得很了不起，我想提建议说原由，但是看了回复我只会很生气，懂吗？感觉你们都很理直气壮，不问缘由

当然你第一条回复是好的，但是后面的换做是你看得下去吗？

**Comment by shihuojian** [comment]
> > > @shihuojian 我觉得你没有用对，你觉得呢？ 其次，我们没有觉得我们自大，更没有觉得自己做的多好，如果你上来无理由喷，那我不好意思，你不尊重我，我也不会尊重你。你把原图发来？
> > 
> > 
> > > 我接受批评，我也接受大家的建议与负面评价，但我希望所有的评价都是基于事实，如果你觉得哪里不对或者不符合预期，我觉得可以向大家一样提出你的问题或者上传的你的样本，如果是我们自身模型的缺陷，我欣然接受，我也愿意去改进，如果是使用的问题，我相信我有空看到就会帮你去解决，也有社区的同伴帮你去解决。
> > 
> > 
> > #108 里面你们回复会让我觉得你们很自大，感觉你们都觉得很了不起，我想提建议说原由，但是看了回复我只会很生气，懂吗？感觉你们都很理直气壮，不问缘由
> 
> 当然你第一条回复是好的，但是后面的换做是你看得下去吗？

#108 我是键盘侠你们都很牛逼

**Comment by wondervictor** [comment]
#108 issue的回答基于事实。我们没觉得我们了不起，我认为有问题你可以讲，但是如果带着“建议取消当前项目，造轮子意义不大，这个项目并没有什么优势，完全逊色于grounding-sam“这样的标题与问题，请问？我们作何感受？辛辛苦苦做这些，然后被无端喷”建议取消“，”意义不大“，”没什么优势“，以及”完全逊色“。请问，如果你有问题，你觉得不好，上来就是这样说话的吗？所有的issues我都会尊重、感谢关注，并自己去想办法尽快解决，要不你去看看？

**Comment by shihuojian** [comment]
> 意义不大

你们完全可以问原因，但是你们回复的都是啥？当然我表达确实有问题
“so, where's your project?”
“show me your code“
”看到标题真呕了呀，我知道你想出名，但为何在此自取其辱？“
”建议喷子不要自以为是站在自己的角度去diss！有种你也发一篇cvpr！

**Comment by wondervictor** [comment]
我替这些回答向你道歉，我不认为我的回复很自大。其次，如果你受不了大众对你“评价别人”这件事认可，那我也希望你也去接受别人对你的“评价”。中国人讲究和气，我说了，你有问题你就说，我不接受无端的抨击。你如果这么对待别人，别人这么对待你的时候，请不要觉得难受。

**Comment by wondervictor** [comment]
你提出第一个issue的时候，没有提供任何问题信息，请问，这是一条想交流问题的issue吗？我不觉得。

**Comment by KTXKIKI** [comment]
> 你提出第一个issue的时候，没有提供任何问题信息，请问，这是一条想交流问题的issue吗？我不觉得。

哥  我也想进鹅厂  加个v可以不  我把简历发你  你看看我有机会不

**Comment by shihuojian** [comment]
> 我替这些回答向你道歉，我不认为我的回复很自大。其次，如果你受不了大众对你“评价别人”这件事认可，那我也希望你也去接受别人对你的“评价”。中国人讲究和气，我说了，你有问题你就说，我不接受无端的抨击。你如果这么对待别人，别人这么对待你的时候，请不要觉得难受。



> 你提出第一个issue的时候，没有提供任何问题信息，请问，这是一条想交流问题的issue吗？我不觉得。

我也觉得没意义，所以关闭了issue。有些你们团队人员回复的啊

**Comment by Ying-Kang** [comment]
非腾讯员工，非项目相关，我最近一直关注这个项目，今天一进来一直在吃瓜

说实话你问出这个问题来，你得多玻璃心，你觉得你说出这种话我们会怎么看你？同时别人看到这个项目会怎么想？

你不反思一下自己说话方式和做事方式，你急功近利想“拿来主义”，出言不逊更自我为中心要求别人对你怎么样怎么样，

你宽带费交的是真的值。

你也是真的偷懒，这些代码但凡有点基础，想改用起来真的不难。

另外回复你的项目组成员，本应该用来好好推进开源的宝贵时间，用来去给你“答疑解惑”以及去做这种无意义的争吵。

如果你是真心想学习，你会用这样的去问你线下的老师吗？

你上学的时候，听不懂老师讲的东西，会跟老师说：你教的什么东西？学校关了吧别开了，嗯？

知道为什么大家对你态度不好不，没有一个想学习的人请教别人会用这样的语气，我觉得负责回复你的人做的仁至义尽了

我觉得是个正常人，也只会觉得问题主要在你

**Comment by shihuojian** [comment]
> 你提出第一个issue的时候，没有提供任何问题信息，请问，这是一条想交流问题的issue吗？我不觉得。

你们团队人说我是键盘侠、盘子、没种，这能忍！

**Comment by wondervictor** [comment]
我想知道，你在最上面 @ 的人，有人说你吗？

**Comment by shihuojian** [comment]
> 我想知道，你在最上面 @ 的人，有人说你吗？

#108 

> 非腾讯员工，非项目相关，我最近一直关注这个项目，今天一进来一直在吃瓜
> 
> 说实话你问出这个问题来，你得多玻璃心，你觉得你说出这种话我们会怎么看你？同时别人看到这个项目会怎么想？
> 
> 你不反思一下自己说话方式和做事方式，你急功近利想“拿来主义”，出言不逊更自我为中心要求别人对你怎么样怎么样，
> 
> 你宽带费交的是真的值。
> 
> 你也是真的偷懒，这些代码但凡有点基础，想改用起来真的不难。
> 
> 另外回复你的项目组成员，本应该用来好好推进开源的宝贵时间，用来去给你“答疑解惑”以及去做这种无意义的争吵。
> 
> 如果你是真心想学习，你会用这样的去问你线下的老师吗？
> 
> 你上学的时候，听不懂老师讲的东西，会跟老师说：你教的什么东西？学校关了吧别开了，嗯？
> 
> 知道为什么大家对你态度不好不，没有一个想学习的人请教别人会用这样的语气，我觉得负责回复你的人做的仁至义尽了
> 
> 我觉得是个正常人，也只会觉得问题主要在你

> 觉得是个正常人，也只会觉得问题主要在你



> 会怎么看你？同时别人看到这个项目会怎么想？

第二天我就已经把issue关闭，但是今早他们说我是喷子，键盘侠。没种，我能忍！

**Comment by wondervictor** [comment]
我替大家对你的评价给你道歉，非常抱歉，如果你有问题，我也欢迎你来提问，我也会尽量帮到你。

**Comment by shihuojian** [comment]
> 我替大家对你的评价给你道歉，非常抱歉，如果你有问题，我也欢迎你来提问，我也会尽量帮到你。

@QzYER 不要动不动就说别人是喷子、键盘侠、有种你干啥干啥来着。我要这些说你也不开心，issue我早就关闭了，你还还这些就真过分了

**Comment by wondervictor** [comment]
我建议打住，现在是开源项目的讨论，我不希望上升到个人攻击了，大家也只是基于你最初的issue内容做的回复，如果大家沟通清楚问题，我觉得可以停住了。大家都是彼此尊重，我希望就此停罢。

**Comment by shihuojian** [comment]
> 我建议打住，现在是开源项目的讨论，我不希望上升到个人攻击了，大家也只是基于你最初的issue内容做的回复，如果大家沟通清楚问题，我觉得可以停住了。大家都是彼此尊重，我希望就此停罢。

我不知道这是不是你们团队的，但是这素质，是的话趁早开了吧
![屏幕截图 2024-03-11 160426](https://github.com/AILab-CVC/YOLO-World/assets/19809313/a1d7047f-bf72-4f8a-82c5-a55ee115f58d)

**Comment by wondervictor** [comment]
有关于YOLO-World的问题讨论可以移步新的issues，本issue决定lock。
