### ISSUE TITLE
About the S model speed and fps

### ISSUE THREAD

**Issue by hyosong86** [AILab-CVC/YOLO-World#113]
I am observing that the S model operates at around 20 fps.

I have conducted tests on both the TitanV and A6000 GPUs, and there isn't a significant difference in performance between the two. 
For the time measurements, I have excluded the time taken for drawing boxes using cv2 and saving images. Only the preprocessing of the input image and the model inference time have been measured.
The time is averaged on inferring a total of 1,000 images.

According to the paper, it achieves 50 fps on a V100 GPU. Based on benchmarks, the performance difference between the V100 and the two GPUs I tested does not seem to be substantial. What could be the reason for this discrepancy?

From my understanding, since the preprocessing step resizes the input image resolution to 640x640, the difference in speed due to the resolution of the input image should not be significant.

**Comment by wondervictor** [comment]
Hi @hyosong86, we measure the inference time of YOLO-World without post-processing steps. In addition, for accurate latency measurement, you need to `synchronize` to avoid asynchronous operations and warmup the inference before calculating the latency

**Comment by large-ocr-model** [comment]
"Could you please provide code for testing speed?"

**Comment by rangmiao** [comment]
"Could you please provide code for testing speed?"

**Comment by wondervictor** [comment]
Hi @rangmiao, sure, while it may be updated later.
