### ISSUE TITLE
关于训练

### ISSUE THREAD

**Issue by dikapiliao1** [AILab-CVC/YOLO-World#116]
请问4块GPU能训练吗

**Comment by wondervictor** [comment]
可以训，不过我建议finetune，pre-train的话开销会很大

**Comment by dikapiliao1** [comment]
估计要多久呢~

**Comment by wondervictor** [comment]
4卡如果是fine-tune COCO的话，80个epoch 应该在1天内，但是如果是pre-train模型的话，应该比较长（目前32卡需要2天时间）。如果你实在需要修改pre-trained模型，可以下载我们提供的weights，然后在pre-train data上继续微调模型，这个比较有效，我们`YOLO-World-v2-L-1280`大尺寸输入也是采用继续微调的方式去实现的，性能会更好。

**Comment by wondervictor** [comment]
Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
