### ISSUE TITLE
中文提示词

### ISSUE THREAD

**Issue by mingxingpu** [AILab-CVC/YOLO-World#121]
您好，我想请教一下如果使用中文做提示词是需要重新训练整个模型吗？或者是修改代码中的文本特征编码器为中文CLIP就可以呢？    期待您的回复！

**Comment by wondervictor** [comment]
@mingxingpu 您好，目前来说，我们用的CLIP是不支持中文的，也无法直接替换中文CLIP来做，两个预训练CLIP并没有对齐，所以直接替换不可行，可取的方案是重新去训练模型了。

**Comment by mingxingpu** [comment]
谢谢您的回复！

**Comment by wondervictor** [comment]
Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
