### ISSUE TITLE
Bugs about demo and image demo

### ISSUE THREAD

**Issue by douyh** [AILab-CVC/YOLO-World#123]
I inference the same image with prompt [["dog"], [" "]].  Everything is OK.
For the same image, I change my text to [["cat"], [" "]]. 
The model can't detect cat but still dog. Only label changed.

Changing the text only can't work well, how can I solve it?

**Comment by douyh** [comment]
![image](https://github.com/AILab-CVC/YOLO-World/assets/34704737/5149c502-1402-42da-bb03-a73a7ab30a98)

I remove the cache, but it does not work.🥲
![image](https://github.com/AILab-CVC/YOLO-World/assets/34704737/d01d33f6-479d-4896-9b5f-f8fd43e7f5d6)

![image](https://github.com/AILab-CVC/YOLO-World/assets/34704737/3278cbcb-6ff5-4f28-ac66-dc961db20293)

**Comment by wondervictor** [comment]
Hi @douyh, could you check whether the text has been updated in the second run?

**Comment by douyh** [comment]
@wondervictor Thanks a lot. I found some bugs in my conda environment. It works for me after I fix my own bugs.

**Comment by wondervictor** [comment]
You're welcome : )

**Comment by wondervictor** [comment]
Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
