### ISSUE TITLE
How to organize Text JSON file?

### ISSUE THREAD

**Issue by Ying-Kang** [AILab-CVC/YOLO-World#124]
I have a large amount of images, each image has captions and labeld bboxes

I've read doc in https://github.com/AILab-CVC/YOLO-World/blob/master/docs/data.md
![image](https://github.com/AILab-CVC/YOLO-World/assets/32356801/3fefd0fa-1da5-4290-ad41-81eb39b1d26f)
 what I should do is like:
```python
[
["caption1"],
["caption2"],
["caption3"],
...
["captionn"],
]
```
or 
```python
[
["caption1 main word1",  "caption1 main word2", ...],
["caption2 main word1",  "caption2 main word2", ...],
["caption3 main word1",  "caption3 main word2", ...],
...
["captionn main word1",  "captionn main word2", ...],,
]
```
above means roughly input all captions or input specified word in caption

which style should be better for trainning?

besides, both style input maybe create a mass of text labels, 

is that right for the following training?

I'd appreciate it if you could help

thx anyway

**Comment by wondervictor** [comment]
Hi @Ying-Kang，
The two cases you provided do work.

(1) If your datasets have some simple categories, you can directly write the JSON file as follows:

```
[['class_a'], ['class_b'], ..., ['class_n']]
```

(2) If your datasets have some categories with synonyms, you can write the JSON file as follows:

```
[
  ['class_a', 'class_a_syn1', 'class_a_syn2'],
  ['class_b', 'class_b_syn1'],
  ..
   ['class_n', ]
]
```

`MultiModalDataset` with a JSON file is suitable for normal detection datasets with pre-defined categories, such as COCO or Objects365.

If you have some grounding datasets with rich texts or noun phrases, I suggest you use the `MixedGroundingDataset` which specifies the `text` for each bounding box.

**Comment by Ying-Kang** [comment]
wow, cool job, 

I'll explore `MixedGroundingDataset`
