### ISSUE TITLE
运行image_demo.py报错

### ISSUE THREAD

**Issue by Longleaves** [AILab-CVC/YOLO-World#125]
使用的命令是：
python image_demo.py configs/pretrain/yolo_world_s_dual_vlpan_l2norm_2e-3_100e_4x8gpus_obj365v1_goldg_train_lvis_minival.py models/yolo_world_seg_m_dual_vlpan_2e-4_80e_8gpus_allmodules_finetune_lvis-ca465825.pth  data/images/ 'person,dog,cat' --topk 100 --threshold 0.005 --output-dir demo_outputs/

报错内容是：
ModuleNotFoundError: No module named 'mmcv._ext'
ImportError: Failed to import yolo_world
You should set `PYTHONPATH` to make `sys.path` include the directory which contains your custom module

我已pip install -e .
请问这上面报错怎么解决呀？

**Comment by wondervictor** [comment]
这个看起来mmcv没有装好，可以单独安装一下看看

**Comment by Longleaves** [comment]
> 这个看起来mmcv没有装好，可以单独安装一下看看

装哪个版本合适呀

**Comment by wondervictor** [comment]
2.0.0应该就可以

**Comment by Longleaves** [comment]
> 2.0.0应该就可以

您好，我重新下载了mmcv2.0.0，然后同样的命令运行，报错了。似乎是要从huggingface下载什么文件？需要配置什么文件吗
![图片](https://github.com/AILab-CVC/YOLO-World/assets/58903935/fd8aaf90-e8cd-43d3-884d-9ecb7a1c2ba6)
![图片](https://github.com/AILab-CVC/YOLO-World/assets/58903935/f3eb3a79-1350-4d63-86ad-657361b475ae)

**Comment by taofuyu** [comment]
> huggingface

READMDE里有huggingface的镜像网站，替换了就行

**Comment by Longleaves** [comment]
> > huggingface
> 
> READMDE里有huggingface的镜像网站，替换了就行

在哪个文件中替换呀？

**Comment by taofuyu** [comment]
> > > huggingface
> > 
> > 
> > READMDE里有huggingface的镜像网站，替换了就行
> 
> 在哪个文件中替换呀？

config里model_name

**Comment by Longleaves** [comment]
> > > > huggingface
> > > 
> > > 
> > > READMDE里有huggingface的镜像网站，替换了就行
> > 
> > 
> > 在哪个文件中替换呀？
> 
> config里model_name

有没有可能把默认下载的网址改成镜像的？

**Comment by taofuyu** [comment]
> > > > > huggingface
> > > > 
> > > > 
> > > > READMDE里有huggingface的镜像网站，替换了就行
> > > 
> > > 
> > > 在哪个文件中替换呀？
> > 
> > 
> > config里model_name
> 
> 有没有可能把默认下载的网址改成镜像的？

你直接在镜像网站里把需要的模型全下到本地，然后config里指定本地路径就行了，速度还快

**Comment by Longleaves** [comment]
> > > > > > huggingface
> > > > > 
> > > > > 
> > > > > READMDE里有huggingface的镜像网站，替换了就行
> > > > 
> > > > 
> > > > 在哪个文件中替换呀？
> > > 
> > > 
> > > config里model_name
> > 
> > 
> > 有没有可能把默认下载的网址改成镜像的？
> 
> 你直接在镜像网站里把需要的模型全下到本地，然后config里指定本地路径就行了，省得麻烦

解决啦，谢谢大佬。然后遇到#110的问题应该用#94的方法解决吗，还是说在更新中？
![图片](https://github.com/AILab-CVC/YOLO-World/assets/58903935/60f528a0-9872-4255-a1ef-7d26bda8c596)

**Comment by Longleaves** [comment]
您好，请问是我哪里没配对吗，怎么那么多错的框。我用的s模型，命令是：
python demo.py configs/pretrain/yolo_world_s_dual_vlpan_l2norm_2e-3_100e_4x8gpus_obj365v1_goldg_train_lvis_minival.py models/yolo_world_seg_m_dual_vlpan_2e-4_80e_8gpus_allmodules_finetune_lvis-ca465825.pth
![图片](https://github.com/AILab-CVC/YOLO-World/assets/58903935/c9734f57-5a42-4ee2-a35a-598ab5f192c6)

**Comment by wondervictor** [comment]
@Longleaves 你这边修改了哪些东西

**Comment by taofuyu** [comment]
> > > > > > > huggingface
> > > > > > 
> > > > > > 
> > > > > > READMDE里有huggingface的镜像网站，替换了就行
> > > > > 
> > > > > 
> > > > > 在哪个文件中替换呀？
> > > > 
> > > > 
> > > > config里model_name
> > > 
> > > 
> > > 有没有可能把默认下载的网址改成镜像的？
> > 
> > 
> > 你直接在镜像网站里把需要的模型全下到本地，然后config里指定本地路径就行了，省得麻烦
> 
> 解决啦，谢谢大佬。然后遇到[#110]的问题应该用[#94]的方法解决吗，还是说在更新中？ ![图片](https://private-user-images.githubusercontent.com/58903935/312342440-60f528a0-9872-4255-a1ef-7d26bda8c596.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMTc2MDcsIm5iZiI6MTcxMDMxNzMwNywicGF0aCI6Ii81ODkwMzkzNS8zMTIzNDI0NDAtNjBmNTI4YTAtOTg3Mi00MjU1LWExZWYtN2QyNmJkYThjNTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA4MDgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllOTdlODAzNGNjYTYzMTZhZDVkNGRhMDE5YmU1ZDFiODgwMGQ5MzA5Y2ViMGM2YTU2NTBiYjdkOThjODhhM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9weZEl7C-SkY3Zn6JYmsZu12XqqlkVtfAam2W469KNA)

把image_demo.py版本回退下就好了，本来没啥问题，这个[PR](https://github.com/AILab-CVC/YOLO-World/pull/73#issuecomment-1993111995)给改错了

**Comment by Longleaves** [comment]
> @Longleaves 你这边修改了哪些东西

没有修改任何东西哦

**Comment by Longleaves** [comment]
> > > > > > > > huggingface
> > > > > > > 
> > > > > > > 
> > > > > > > READMDE里有huggingface的镜像网站，替换了就行
> > > > > > 
> > > > > > 
> > > > > > 在哪个文件中替换呀？
> > > > > 
> > > > > 
> > > > > config里model_name
> > > > 
> > > > 
> > > > 有没有可能把默认下载的网址改成镜像的？
> > > 
> > > 
> > > 你直接在镜像网站里把需要的模型全下到本地，然后config里指定本地路径就行了，省得麻烦
> > 
> > 
> > 解决啦，谢谢大佬。然后遇到[#110]的问题应该用[#94]的方法解决吗，还是说在更新中？ ![图片](https://private-user-images.githubusercontent.com/58903935/312342440-60f528a0-9872-4255-a1ef-7d26bda8c596.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMTc2MDcsIm5iZiI6MTcxMDMxNzMwNywicGF0aCI6Ii81ODkwMzkzNS8zMTIzNDI0NDAtNjBmNTI4YTAtOTg3Mi00MjU1LWExZWYtN2QyNmJkYThjNTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA4MDgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllOTdlODAzNGNjYTYzMTZhZDVkNGRhMDE5YmU1ZDFiODgwMGQ5MzA5Y2ViMGM2YTU2NTBiYjdkOThjODhhM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9weZEl7C-SkY3Zn6JYmsZu12XqqlkVtfAam2W469KNA)
> 
> 把image_demo.py版本回退下就好了，本来没啥问题，这个[PR](https://github.com/AILab-CVC/YOLO-World/pull/73#issuecomment-1993111995)给改错了

demo.py也是图片上那样咧

**Comment by taofuyu** [comment]
可能你pth用的分割的吧

**Comment by Longleaves** [comment]
> 您好，请问是我哪里没配对吗，怎么那么多错的框。我用的s模型，命令是： python demo.py configs/pretrain/yolo_world_s_dual_vlpan_l2norm_2e-3_100e_4x8gpus_obj365v1_goldg_train_lvis_minival.py models/yolo_world_seg_m_dual_vlpan_2e-4_80e_8gpus_allmodules_finetune_lvis-ca465825.pth ![图片](https://private-user-images.githubusercontent.com/58903935/312350758-c9734f57-5a42-4ee2-a35a-598ab5f192c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODYwMDQsIm5iZiI6MTcxMDM4NTcwNCwicGF0aCI6Ii81ODkwMzkzNS8zMTIzNTA3NTgtYzk3MzRmNTctNWE0Mi00ZWUyLWEzNWEtNTk4YWI1ZjE5MmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDAzMDgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NWYyMDhiNjM0YjNkODc4ODllODA5N2Q2ZjI2ODQ5M2NhZjc2M2NmZDdkNzM1YWY5M2U0Yzk0YzZhNGM5ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z5Qize7lkBxo5bD1RYz-BmzQK61goPpEJoUrWXMwp18)

是配错了模型，用成了seg，改成YOLO_WORLD_S就好啦。感谢你们！谢谢！

**Comment by Longleaves** [comment]
你们好，我第一次运行person, bus没有问题，如图1，第二只写了bus再提交就变成图2这样person的框也变成bus了。这是为什么呀？按clear以后也会显示错误，图3。
![图片](https://github.com/AILab-CVC/YOLO-World/assets/58903935/c47a61f2-57b4-498b-8570-cde6a82178b0)
![图片](https://github.com/AILab-CVC/YOLO-World/assets/58903935/b38a79db-d1db-4389-a763-71dd65776d77)
![图片](https://github.com/AILab-CVC/YOLO-World/assets/58903935/eb68bb76-6b46-4cbc-92e6-70ae23b9d7ee)

**Comment by fgd0707** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\YOLO-World-master\\configs\\pretrain\\../../third_party/mmyolo/configs/yolov8/yolov8_s_syncbn_fast_8xb16-500e_coco.py'
哥哥们 这个错误是咋回事，我mmyolo里没有他这个东西

**Comment by fgd0707** [comment]
> > > > > > > > > huggingface
> > > > > > > > 
> > > > > > > > 
> > > > > > > > READMDE里有huggingface的镜像网站，替换了就行
> > > > > > > 
> > > > > > > 
> > > > > > > 在哪个文件中替换呀？
> > > > > > 
> > > > > > 
> > > > > > config里model_name
> > > > > 
> > > > > 
> > > > > 有没有可能把默认下载的网址改成镜像的？
> > > > 
> > > > 
> > > > 你直接在镜像网站里把需要的模型全下到本地，然后config里指定本地路径就行了，省得麻烦
> > > 
> > > 
> > > 解决啦，谢谢大佬。然后遇到[#110]的问题应该用[#94]的方法解决吗，还是说在更新中？ ![图片](https://private-user-images.githubusercontent.com/58903935/312342440-60f528a0-9872-4255-a1ef-7d26bda8c596.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMTc2MDcsIm5iZiI6MTcxMDMxNzMwNywicGF0aCI6Ii81ODkwMzkzNS8zMTIzNDI0NDAtNjBmNTI4YTAtOTg3Mi00MjU1LWExZWYtN2QyNmJkYThjNTk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA4MDgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllOTdlODAzNGNjYTYzMTZhZDVkNGRhMDE5YmU1ZDFiODgwMGQ5MzA5Y2ViMGM2YTU2NTBiYjdkOThjODhhM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9weZEl7C-SkY3Zn6JYmsZu12XqqlkVtfAam2W469KNA)
> > 
> > 
> > 把image_demo.py版本回退下就好了，本来没啥问题，这个[PR](https://github.com/AILab-CVC/YOLO-World/pull/73#issuecomment-1993111995)给改错了
> 
> demo.py也是图片上那样咧

哥 这个class_id报错咋解决的 可以告诉下吗

**Comment by wondervictor** [comment]
@fgd0707 用最新的code，已经fix了

**Comment by wondervictor** [comment]
Hi all, the bug in the `demo.py` has been fixed, you can have a try! BTW, ONNX export is also supported!

**Comment by ccl-private** [comment]
我找不到pth模型下载的地方，这边只有一个模型：https://huggingface.co/spaces/stevengrove/YOLO-World/tree/main，而且找不到对应的config？

**Comment by ccl-private** [comment]
莫非是这个？：https://huggingface.co/wondervictor/YOLO-World/tree/main
