### ISSUE TITLE
finetune阶段中，open-vocabulary 和close-set 区别是什么呢？

### ISSUE THREAD

**Issue by liuhuiCNN** [AILab-CVC/YOLO-World#128]
比如我的应用场景是检测穿不同颜色衣服的行人（如穿蓝色和红色衣服的行人）。
这种场景下如何标注数据，如何finetune比较好呢？
finetune过程是使用efficient neck结构好还是不使用efficient neck结构好呢？
谢谢！

**Comment by wondervictor** [comment]
如果需求只有这样的话，我建议就按照颜色来标一部分数据。不过我建议在fine-tune阶段保留neck和language model，但是infer的时候可以去除。用了efficientneck就丧失本身的zero-shot和language understanding能力了。

**Comment by KDgggg** [comment]
> 如果需求只有这样的话，我建议就按照颜色来标一部分数据。不过我建议在fine-tune阶段保留neck和language model，但是infer的时候可以去除。用了efficientneck就丧失本身的zero-shot和language understanding能力了。

你好 我还想问一下自定义数据集格式得按照coco格式吗，然后自定义类别text会利用clip来匹配我们自定义的类别吗

**Comment by wondervictor** [comment]
> 你好 我还想问一下自定义数据集格式得按照coco格式吗，然后自定义类别text会利用clip来匹配我们自定义的类别吗

@KDgggg 目前数据的话是支持COCO格式（COCO格式目前比较通用），可以为每一个box标注提供一段text，不一定强直定义`categories`。目前没有clip去做匹配的事情。
