### ISSUE TITLE
关于分割

### ISSUE THREAD

**Issue by xiyangyang99** [AILab-CVC/YOLO-World#129]
利用官方提供的分割权重和config，分割output里面似乎没有分割mask。image_demo.py支持instance segment嘛？

**Comment by wondervictor** [comment]
@QzYER demo目前不支持分割可视化

**Comment by Ningchuan-Li** [comment]
我是对demo.py增加以下代码实现分割可视化的：
- 23行：MASK_ANNOTATOR = sv.MaskAnnotator()
- 77行：mask=pred_instances['masks']
- 88行：image = MASK_ANNOTATOR.annotate(image, detections)

**Comment by QzYER** [comment]
> 我是对demo.py增加以下代码实现分割可视化的：
> 
> * 23行：MASK_ANNOTATOR = sv.MaskAnnotator()
> * 77行：mask=pred_instances['masks']
> * 88行：image = MASK_ANNOTATOR.annotate(image, detections)

**perfect！**

**Comment by wondervictor** [comment]
@xiyangyang99 `image_demo`目前已经支持分割可视化，感谢 @Ningchuan-Li  提供的有效建议！

**Comment by wondervictor** [comment]
Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
