### ISSUE TITLE
Clicking Clear will cause an Error

### ISSUE THREAD

**Issue by pg56714** [AILab-CVC/YOLO-World#13]
![image](https://github.com/AILab-CVC/YOLO-World/assets/97820073/bcd0bf66-d48b-4ef1-b1d4-525d3932f473)

**Comment by wondervictor** [comment]
Hi @pg56714, I'm sorry for the late late reply. This problem has been fixed already and you can have a try: )

**Comment by wondervictor** [comment]
This issue will be closed since there is no further update related to the main topic. Besides, the error has been fixed already. Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.

**Comment by pg56714** [comment]
@wondervictor 
2024/03/21
There are still errors
![image](https://github.com/AILab-CVC/YOLO-World/assets/97820073/c91eb144-9df3-4d56-8ea0-0fc2dccaef08)

**Comment by wondervictor** [comment]
Try out the demo in this repo.

**Comment by pg56714** [comment]
OK, thanks
