### ISSUE TITLE
Re-parameterizable Vision-Language PAN模块的可重参数化如何体现

### ISSUE THREAD

**Issue by MaverickPigoo** [AILab-CVC/YOLO-World#130]
您好，您在论文中说yolo-world使用了一种可重参数化的视觉-语言路径聚合网络Rep VL-PAN,并提到‘During inference, the offline vocabulary embeddings can be re-parameterized into weights of convolutional or linear layers for deployment.’，请问具体是如何将offline vocabulary embeddings转化为权重的呢，有对应的代码实现吗？

还有论文中Table2中最下面一大栏中比较了yolo-world-(s, m, l)的re-parameterized 版本 (w/o bracket) 和原始版本的参数量区别，请问这里的re-parameterized version (w/o bracket) and the original version (w/ bracket)结构具体有什么区别吗，为什么参数量有这么大差距？
![1710301010912](https://github.com/AILab-CVC/YOLO-World/assets/50261111/e3936822-5a1c-4657-a3d8-3569d81703e3)

**Comment by wondervictor** [comment]
@MaverickPigoo 目前我们没有提供具体的代码实现，这部分可以在转ONNX等模型的时候会体现，实际推理的时候，其实是可以将text embeddings或者finetune后的prompt embeddings作为模型的参数，在RepVL-PAN中，这些embeddings可以转换为1x1conv的weight和图像特征计算，对于head部分，embeddings可以和batchnorm fuse在一起然后用作1x1conv来预测。

关于table中的w/ bracke和w/o bracket：w/bracket是带上了text encoder一起推理的fps+参数，w/o bracket是提前计算好embeddings融到模型里的fps+参数，不过这里的融合还比较简单，没有做特殊的操作（将matmul换成1x1conv，以及fuse bn和conv weight）

**Comment by MaverickPigoo** [comment]
那Tabel2中统计GLIP和Grounding Dino等方法的参数量和fps时也是考虑了text encoder的吗？

**Comment by wondervictor** [comment]
是的，目前本地测试的话是考虑了，text encoder时间占比对于像Swin-L/T等较大的模型不是很大，但是对于YOLO这些小模型会比较大。

**Comment by MaverickPigoo** [comment]
了解了，谢谢~

**Comment by wondervictor** [comment]
Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
