### ISSUE TITLE
How many I-Pooling Attention are used in Neck?

### ISSUE THREAD

**Issue by mtjhl** [AILab-CVC/YOLO-World#133]
In your paper's figure, it show two I-Pooling Attention is used. However, in thecode, I only find one?
<img width="452" alt="image" src="https://github.com/AILab-CVC/YOLO-World/assets/107097683/ac906e0d-2750-4aa0-9ace-9c0e2e891fab">

https://github.com/AILab-CVC/YOLO-World/blob/83601a1634276336ddcfd237ba7bbb5b79d86310/yolo_world/models/necks/yolo_world_pafpn.py#L219

Another question, is the Image-aware Embeddings used in the head? In your figure, it means the neck will output the Image-aware Embedding. Howerer, in the code of neck, it does not output it.
Thank you.

**Comment by wondervictor** [comment]
Hi @mtjhl, the I-PoolingAttention forwards only once. It's a wrong description in our paper and we will fix it. The updated text embeddings are used for the next-stage text-to-image guidance.

**Comment by wondervictor** [comment]
@MaverickPigoo 在目前的实现中，updated text embeddings没有加入到head中参与预测，这部分我们会更正过来。

**Comment by wondervictor** [comment]
@MaverickPigoo @mtjhl Considering that the I-PoolingAttention and L2-norm are not efficient enough for TensorRT models, we have removed them for the new version (YOLO-World-V2). All pre-trained checkpoints have been released and we suggest you move to the new version of YOLO-World.

**Comment by xiyangyang99** [comment]
> @MaverickPigoo @mtjhl Considering that the I-PoolingAttention and L2-norm are not efficient enough for TensorRT models, we have removed them for the new version (YOLO-World-V2). All pre-trained checkpoints have been released and we suggest you move to the new version of YOLO-World.

第二个版本的我在转onnx的时候，报错了，貌似是算子的问题，onnx export 过程中，adaptive_avg_pool2好像onnx不支持，第一个版本转onnx的时候没有存在 这个问题；建议你们整个分支或者把第一个版本也放出来；

**Comment by wondervictor** [comment]
@xiyangyang99 第二个版本我们可以会在将来废弃掉，不过你说的换一个分支维护这个我觉得不错。但是目前第v2相比v1没有增加adaptive_avg_pool2呀

**Comment by xiyangyang99** [comment]
> @xiyangyang99 第二个版本我们可以会在将来废弃掉，不过你说的换一个分支维护这个我觉得不错。但是目前第v2相比v1没有增加adaptive_avg_pool2

这是我转的时候bug：
RuntimeError: Unsupported: ONNX export of operator adaptive_max_pool2d, output size that are not factor of input size. Please feel free to request support or submit a pull request on PyTorch GitHub.

**Comment by wondervictor** [comment]
@xiyangyang99, 可以尝试下我们在[`demo.py`](https://github.com/AILab-CVC/YOLO-World/blob/master/demo.py)提供的ONNX转换。
