### ISSUE TITLE
When I try to export a model with a batch greater than 1, the guide variable's batch dimension is still default 1

### ISSUE THREAD

**Issue by wufei-png** [AILab-CVC/YOLO-World#135]
[huggingface.co/spaces/stevengrove/YOLO-World](https://huggingface.co/spaces/stevengrove/YOLO-World)
The code call stack is as follows:

tools/demo.py -> deploy_model(fake_input)

and then:
yolo_world/models/detectors/yolo_world.py ->  
def extract_feat( 
        if batch_data_samples is None:
            texts = self.texts
At this point the texts batch is 1

and then:
yolo_world/models/layers/yolo_bricks.py:-> guide = guide.reshape(B, -1, self.num_heads, self.head_channels)

At this point the guide is the above texts,the Batch dimension is always 1, so will report a reshape error, it looks like it can be improved, judge if the shape(0) of the guide is the batch_size, if not then use the default self.texts to fill it?

**Comment by wufei-png** [comment]
另外想问一下，有对推理性能进行batch的尝试吗，目前的模型看起来输入是只有一张？不知道一次性输入多张会不会提升性能？

**Comment by wondervictor** [comment]
您好，@wufei-png 目前没有做batch维度的扩展，如果是batch去计算，性能肯定会提升的，但是现在受限于mmyolo框架限制就没有做这样的测试。
