### ISSUE TITLE
缺少脚本

### ISSUE THREAD

**Issue by 997897336** [AILab-CVC/YOLO-World#14]
python setup.py build develop

报错：
FileNotFoundError: [Errno 2] No such file or directory: 'yolo_world/version.py'

**Comment by jg0014** [comment]
same problem

**Comment by wondervictor** [comment]
@jg0014 @997897336 Thanks for your reminding. I've fixed it and you can re-install it now.

**Comment by wondervictor** [comment]
Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
