### ISSUE TITLE
More pre-trained YOLO-Worldv2 models with an input resolution of 1280

### ISSUE THREAD

**Issue by liangzhiyuanCV** [AILab-CVC/YOLO-World#142]
Great job! I'm wondering if you have any plans to provide pre-trained model weights for YOLO-Worldv2-s and YOLO-Worldv2-m with an input resolution of 1280. Thank you.

**Comment by wondervictor** [comment]
Hi @liangzhiyuanCV, we are doing it now.

**Comment by wondervictor** [comment]
Hi @liangzhiyuanCV, we have updated with more high-resolution pre-trained checkpoints now.

**Comment by wondervictor** [comment]
This issue will be closed since no further update related to the main topic exists. Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
