### ISSUE TITLE
运行demo.py时clear出现错误

### ISSUE THREAD

**Issue by Longleaves** [AILab-CVC/YOLO-World#143]
第一次运行person, bus没有问题，如图1，第二只写了bus再提交就变成图2这样person的框也变成bus了。这是为什么呀？按clear以后也会显示错误，图3。
图1：
![图片](https://github.com/AILab-CVC/YOLO-World/assets/58903935/c47a61f2-57b4-498b-8570-cde6a82178b0)
图2：
![图片](https://github.com/AILab-CVC/YOLO-World/assets/58903935/b38a79db-d1db-4389-a763-71dd65776d77)
图3：
![图片](https://github.com/AILab-CVC/YOLO-World/assets/58903935/eb68bb76-6b46-4cbc-92e6-70ae23b9d7ee)
图4：
![图片](https://github.com/AILab-CVC/YOLO-World/assets/58903935/f8f115b8-0ed4-4cc6-8513-a82858d3b6e6)

_Originally posted by @Longleaves in https://github.com/AILab-CVC/YOLO-World/issues/125#issuecomment-1996590798_

**Comment by Ying-Kang** [comment]
me too, all labels right while separated single label lead to wrong answer

**Comment by wondervictor** [comment]
Hi @Ying-Kang @Longleaves, this bug has been fixed, you can try the new code now! ONNX export is also supported!

**Comment by fgd0707** [comment]
网址为http://0.0.0.0:8080/ 的页面可能存在问题，或者已永久移动到新的网址。 这个问题大家有吗，demo.py运行后网址打不开

**Comment by wondervictor** [comment]
@fgd0707 可以更换端口试试

**Comment by wondervictor** [comment]
This issue will be closed since there is no further update related to the main topic. Besides, the error has been fixed already. Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
