### ISSUE TITLE
如果我使用coco的dataset進行fine tune是可以使用caption_train2017.json作為ann_file的輸入嗎?

### ISSUE THREAD

**Issue by xianhonghuang** [AILab-CVC/YOLO-World#144]
如題

**Comment by wondervictor** [comment]
不是，还是按照instances标注作为输入，可以参照我们提供的config

**Comment by wondervictor** [comment]
没有的，这个是对更为通用的image-text数据做的处理

**Comment by wondervictor** [comment]
This issue will be closed since there is no further update related to the main topic. Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
