### ISSUE TITLE
训练中loss_bbox和loss_dfl第一个epoch就是0，然后训练出来的权重去推理测试，得不到任何结果

### ISSUE THREAD

**Issue by 997897336** [AILab-CVC/YOLO-World#146]
03/18 06:15:39 - mmengine - INFO - Epoch(train)  [1][50/70]  base_lr: 2.0000e-04 lr: 9.8000e-06  eta: 1:58:38  time: 1.2826  data_time: 0.0524  memory: 11573  grad_norm: nan  loss: 331.5620  loss_cls: 331.5620  loss_bbox: 0.0000  loss_dfl: 0.0000
具体配置文件为
![image](https://github.com/AILab-CVC/YOLO-World/assets/78671643/29716c79-3469-409c-92d4-bdf5d61ce028)
![image](https://github.com/AILab-CVC/YOLO-World/assets/78671643/dacb9221-24f7-4051-9896-eb59b9a3afba)
![image](https://github.com/AILab-CVC/YOLO-World/assets/78671643/e063361d-c111-4524-8fa8-5b4c20857be6)

**Comment by 997897336** [comment]
03/18 06:33:35 - mmengine - INFO - Epoch(train) [16][50/70]  base_lr: 2.0000e-04 lr: 1.6535e-04  eta: 1:10:05  time: 0.9005  data_time: 0.0392  memory: 10765  grad_norm: 0.0206  loss: 0.0000  loss_cls: 0.0000  loss_bbox: 0.0000  loss_dfl: 0.0000
训练几轮之后所有的loss都成0了

**Comment by taofuyu** [comment]
没看懂为什么你训练数据是coco但类别数设置的是5

**Comment by 997897336** [comment]
> 没看懂为什么你训练数据是coco但类别数设置的是5

用的是coco格式数据集，不是coco

**Comment by taofuyu** [comment]
> > 没看懂为什么你训练数据是coco但类别数设置的是5
> 
> 用的是coco格式数据集，不是coco

那dataset的类型也要自己写的，不能用Yolov5CocoDataset。 而且text json看起来也是coco的。甚至data_prefix都是train2017/

**Comment by wondervictor** [comment]
@997897336  any update?

**Comment by 997897336** [comment]
这是其中一个标注{"id": 1012, "image_id": 680, "category_id": 1, "segmentation": [], "area": 33077.5888, "bbox": [492.36, 31.01, 213.79, 154.72], "iscrowd": 0, "attributes": {"occluded": false}}, 
text   json是五类
@wondervictor 
”dataset的类型也要自己写的“这个什么意思？ @taofuyu

**Comment by taofuyu** [comment]
For example:

@DATASETS.register_module()
class MyDataset(BatchShapePolicyDataset, CocoDataset):
    """custom dataset."""

    METAINFO = {
        'classes': ('class_1', 'class_2', 'class_3'),
        'palette': [(220, 20, 60), (255, 0, 0), (0, 255, 0)]}

If your dataset is not COCO,  don't use Yolov5CocoDataset, implement your own dataset like this.

**Comment by 997897336** [comment]
大佬可以细说一下咋改的不？ @taofuyu

**Comment by TerryYiDa** [comment]
> 这是其中一个标注{"id": 1012, "image_id": 680, "category_id": 1, "segmentation": [], "area": 33077.5888, "bbox": [492.36, 31.01, 213.79, 154.72], "iscrowd": 0, "attributes": {"occluded": false}}, text json是五类 还是上次说的我用同样的数据集去训练官方的yolox都可以，应该不是数据集标注有问题，可能是我配置文件没写对，但是目前不知道错在哪了
> 
> @wondervictor ”dataset的类型也要自己写的“这个什么意思？ @taofuyu
你好问题解决了吗？我现在存在同样的问题
