### ISSUE TITLE
导出onnx配置文件错误

### ISSUE THREAD

**Issue by 997897336** [AILab-CVC/YOLO-World#148]
root@zmj:/build/YOLO-World# python deploy/deploy.py --deploy-cfg configs/deploy/detection_onnxruntime-fp16_dynamic.py --model-cfg configs/pretrain/yolo_world_x_dual_vlpan_l2norm_2e-3_100e_4x8gpus_obj365v1_goldg_train_lvis_minival.py --checkpoint pretrained_models/yolo_world_x_clip_base_dual_vlpan_2e-3adamw_32xb16_100e_o365_goldg_cc3mlite_train_pretrained-8cf6b025.pth --img data/images/bus.jpg 

报错
usage: deploy.py [-h] [--test-img TEST_IMG [TEST_IMG ...]] [--work-dir WORK_DIR] [--calib-dataset-cfg CALIB_DATASET_CFG] [--device DEVICE] [--log-level {CRITICAL,FATAL,ERROR,WARN,WARNING,INFO,DEBUG,NOTSET}] [--show] [--dump-info]
                 [--quant-image-dir QUANT_IMAGE_DIR] [--quant] [--uri URI]
                 deploy_cfg model_cfg checkpoint img
deploy.py: error: unrecognized arguments: --deploy-cfg --model-cfg --checkpoint --img

**Comment by taofuyu** [comment]
argparse基本用法，这几个值别加--deploy-cfg啥的

**Comment by 997897336** [comment]
谢谢老哥
