### ISSUE TITLE
Support Torch==2.0.0?

### ISSUE THREAD

**Issue by Zi-ang-Cao** [AILab-CVC/YOLO-World#15]
Hey Authors, 
Thanks for the excellent job! I am wandering whether your project can support `pytorch==2.0.0 torchvision==0.15.0 torchaudio==2.0.0 pytorch-cuda=11.8`? Or in general any PyTorch>2.0.0? I believe the runtime efficiency and compatibility of `PyTorch>2.0.0` is way more better for python >= 3.10

Do looking forward to deploying your model, instead of grounding-DINO, in the real-time on-board system.

Thanks!

**Comment by wondervictor** [comment]
Hi @Zi-ang-Cao, thanks for your interest in YOLO-World. We have tested the code of YOLO-World based on `torch=1.1x` and we will test the code for both pre-training or fine-tuning on `torch=2.x`. Considering that YOLO-World has no special operations or APIs, it shall support `torch 2.0`.

**Comment by wondervictor** [comment]
Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
