### ISSUE TITLE
HF demo上的onnx export不能用了

### ISSUE THREAD

**Issue by blacksino** [AILab-CVC/YOLO-World#150]
显示error，请问如何正确导出yolo world v2呢，文档貌似也是空的，谢谢！

**Comment by taofuyu** [comment]
拉最新代码，本地跑demo.py，提供了一个export按钮，和HF一样。
easydeploy里的tools/export_onnx.py

**Comment by wondervictor** [comment]
Hi @blacksino, 以本repo为主吧，后续我们会优化HF上的demo

**Comment by blacksino** [comment]
非常感谢，我已成功导出，但是onnx的推理时貌似只有一个image的输入，如果进行文本的输入呢

**Comment by wondervictor** [comment]
@blacksino 目前ONNX仅支持图像输入，在导入之前需要提前预定义好自己的text prompts。

**Comment by blacksino** [comment]
many thanks.
