### ISSUE TITLE
网址为http://0.0.0.0:8080/ 的页面可能存在问题，或者已永久移动到新的网址

### ISSUE THREAD

**Issue by fgd0707** [AILab-CVC/YOLO-World#152]
我刚更新的代码，运行demo.py就会这样，已经两天了，前两天开过成功过，有一样问题的吗

**Comment by wondervictor** [comment]
这应该是你本地的问题，更换端口再试试。

**Comment by fgd0707** [comment]
> 这应该是你本地的问题，更换端口再试试。

谢谢你 搞定了哥

**Comment by wondervictor** [comment]
This issue will be closed since there is no further update related to the main topic. Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
