### ISSUE TITLE
Bug report about export_onnx.py

### ISSUE THREAD

**Issue by taofuyu** [AILab-CVC/YOLO-World#153]
In deploy/export_onnx.py, it [reparameterize](https://github.com/AILab-CVC/YOLO-World/blob/6c618d2bcbcbfe9a94380f78497c6523d7efd211/deploy/export_onnx.py#L120) text encoder.
`YOLOWorldDetector` has this [interface](https://github.com/AILab-CVC/YOLO-World/blob/6c618d2bcbcbfe9a94380f78497c6523d7efd211/yolo_world/models/detectors/yolo_world.py#L56) but `YOLOWorldPromptDetector` doesn't. Although `YOLOWorldPromptDetector` already has offline text features, but it needs a fake reparameterize() to run export_onnx.py.

**Comment by wondervictor** [comment]
Hi, I ignored the `PromptDetector` for ONNX models and I'll add it.
