### ISSUE TITLE
how can we get lvis_v1_class_captions.json

### ISSUE THREAD

**Issue by Glorainow** [AILab-CVC/YOLO-World#17]
when evaluating on lvis，it reports a lack of file "lvis_v1_class_captions.json"，how can we get this file?

**Comment by wondervictor** [comment]
Hi @DarkerDreamer, we have added the text json files in `data/texts`.

**Comment by wondervictor** [comment]
Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.

**Comment by DarkerDreamer** [comment]
My pleasure
