### ISSUE TITLE
onnx导出问题

### ISSUE THREAD

**Issue by Rickustc** [AILab-CVC/YOLO-World#170]
采用项目提供的export_onnx.py  导出代码导出onnx文件：
` PYTHONPATH=./ python deploy/export_onnx.py "YOLO-World/configs/pretrain/yolo_world_s_dual_vlpan_l2norm_2e-3_100e_4x8gpus_obj365v1_goldg_train_lvis_minival.py" "YOLO-World/pretrained_weights/yolo_world_s_clip_base_dual_vlpan_2e-3adamw_32xb16_100e_o365_goldg_train_pretrained-18bea4d2.pth" --custom-text "YOLO-World/deploy/customtxt.json" --opset 13`

报错：
`torch.onnx.errors.SymbolicValueError: Unsupported: ONNX export of operator adaptive_max_pool2d, output size that are not factor of input size. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues  [Caused by the value '931 defined in (%931 : Long(2, strides=[1], device=cpu) = onnx::Constant[value= 3  3 [ CPULongType{2} ]]()`
查看作者在huggingface上提供的onnx中文件没有这个算子，我有哪方面的操作没有对齐吗？

**Comment by wondervictor** [comment]
I suggest you use the `v2.0` of YOLO-World. The `adaptive_xxx_pooling` is not friendly for static graphs.

**Comment by Rickustc** [comment]
> I suggest you use the `v2.0` of YOLO-World. The `adaptive_xxx_pooling` is not friendly for static graphs.

感谢这么快的回复！:)

**Comment by Hstwhale** [comment]
> I suggest you use the `v2.0` of YOLO-World. The `adaptive_xxx_pooling` is not friendly for static graphs.

请问如何换到v2.0呢？没看到有分支呀。

**Comment by zzqiuzz** [comment]
@Rickustc hello 预训练的权重在哪里能下载呢
