### ISSUE TITLE
论文中的Params和FPS是如何计算的？

### ISSUE THREAD

**Issue by JiayuanWang-JW** [AILab-CVC/YOLO-World#177]
请问您的Params在训练或测试的log中有体现吗？我并没有在log中找到相关的信息，您是自己单独写的程序去计算的Params和FPS吗？请问可以开源出来吗？我尝试使用YOLO-World/third_party/mmyolo/tools/analysis_tools/get_flops.py去计算，但是失败了，TypeError: batch_data_samples should be dict or list.

FPS的计算可能受到预热等影响比较大，所以希望得到您准确的FPS测试方式，谢谢。

**Comment by wondervictor** [comment]
Hi @JiayuanWang-JW, parameters are computed through the modified`get_flops.py` by removing the computation of FLOPs. FPS is measured with two settings: w/  text encoder and w/o text encoder. We will add the scripts later considering that there are still many issues that need to be addressed as a priority at this moment.

**Comment by JiayuanWang-JW** [comment]
Thanks. After modifying the get_flops.py, I got the Params.

**Comment by lynshwoo2022** [comment]
hi there,
have you solved this problem? can get_flops work now?

**Comment by ZhitaoWen** [comment]
> Hi [@JiayuanWang-JW](https://github.com/JiayuanWang-JW), parameters are computed through the modified`get_flops.py` by removing the computation of FLOPs. FPS is measured with two settings: w/ text encoder and w/o text encoder. We will add the scripts later considering that there are still many issues that need to be addressed as a priority at this moment.

Sorry to bother you, but where can I find the “modified get_flop.py” code?
