### ISSUE TITLE
找不到配置文件

### ISSUE THREAD

**Issue by 997897336** [AILab-CVC/YOLO-World#18]
![2401d313-81fc-4698-8f64-0a5003b93b0d](https://github.com/AILab-CVC/YOLO-World/assets/78671643/231c9f92-6c1e-459e-801a-e25313526904)
新的readme中好像没有创建third_party文件夹这一步

**Comment by wondervictor** [comment]
可以尝试在本地创建third_party然后clone一个mmyolo下来，这块我们继续check&优化一下

**Comment by 997897336** [comment]
嗯呢

**Comment by wondervictor** [comment]
Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
