### ISSUE TITLE
nms needed?

### ISSUE THREAD

**Issue by HeChengHui** [AILab-CVC/YOLO-World#184]
when looking at both the [demo script ](https://github.com/AILab-CVC/YOLO-World/blob/master/image_demo.py)and [inference notebook](https://github.com/AILab-CVC/YOLO-World/blob/master/inference.ipynb), it seems like the notebook has an extra NMS block:

```
with autocast(enabled=False), torch.no_grad():
        output = runner.model.test_step(data_batch)[0]
        runner.model.class_names = texts
        pred_instances = output.pred_instances

# nms
keep_idxs = nms(pred_instances.bboxes, pred_instances.scores, iou_threshold=nms_thr)
pred_instances = pred_instances[keep_idxs]
pred_instances = pred_instances[pred_instances.scores.float() > score_thr]

if len(pred_instances.scores) > max_num_boxes:
        indices = pred_instances.scores.float().topk(max_num_boxes)[1]
        pred_instances = pred_instances[indices]
    output.pred_instances = pred_instances
```

but is not present in the demo script. Is the NMS needed?

**Comment by wondervictor** [comment]
Hi @HeChengHui, `test_step` contains `nms` operation. The extra `nms` in the `demo.py` provides a further duplicate removal for users.

**Comment by HeChengHui** [comment]
@wondervictor 
so if i still see a lot of duplicates i should add in the `nms` block?

**Comment by wondervictor** [comment]
You can lower down the IoU threshold to a smaller value, thus removing the duplicates.
