### ISSUE TITLE
在自定义数据集上复现不成功

### ISSUE THREAD

**Issue by 997897336** [AILab-CVC/YOLO-World#185]
这个问题还是没有解决，coco数据集格式，有五类，配置文件是

![image](https://github.com/AILab-CVC/YOLO-World/assets/78671643/e98dd914-1176-4c2a-a6bf-16f4a456fee3)

问题是
![image](https://github.com/AILab-CVC/YOLO-World/assets/78671643/f1b353a8-ae7c-4948-bbb9-4930f62c5b91)

这两个loss从一开始就是0，loss_bbox: 0.0000 loss_dfl: 0.0000，还会出现The testing results of the whole dataset is empty.的报错，但是训练会继续进行，到最后得到一个权重，测试得不到任何结果

**Comment by wondervictor** [comment]
Hi @997897336, it's a bit hard to debug since I do not have your custom data. Could you try:
1. reduce the learning rate to 1e-5,
2. share more details about your config
?

**Comment by wondervictor** [comment]
@997897336 any update?

**Comment by lossfaller** [comment]
@997897336 有解决吗最后

**Comment by HarryBarry123** [comment]
I encountered the same issue where there is no data input in the data_batch of utils.py, but the first two loss terms exist.

**Comment by ErwinCheung** [comment]
The possible reason is that there is no "segmentation" field in your annotated JSON file. Adding this field should resolve the issue.

**Comment by kitsch717** [comment]
It may also be that you don't have the segmentation dataset, but you've used the config file related to mask - refine.
For example, you can replace
base = ('../../third_party/mmyolo/configs/yolov8/'
'yolov8_s_mask-refine_syncbn_fast_8xb16-500e_coco.py')
with
base = ('../../third_party/mmyolo/configs/yolov8/'
'yolov8_s_syncbn_fast_8xb16-500e_coco.py')
and delete
min_area_ratio=_base_.min_area_ratio,
use_mask_refine=_base_.use_mask2refine
……
Probably you can try the operations described above.
