### ISSUE TITLE
Hi, I have a question, why the results of Zero-shot Evaluation on LVIS at readme are different with table2 in the paper?

### ISSUE THREAD

**Issue by KindredSpirithub** [AILab-CVC/YOLO-World#188]
<img width="661" alt="b2ec8abc2bd6b8ab4ebe6cce6d8666e" src="https://github.com/AILab-CVC/YOLO-World/assets/38314189/b73f0d5e-0704-47a5-bd20-3375644bf390">
<img width="770" alt="51153e17bde40fb14018322887adcd2" src="https://github.com/AILab-CVC/YOLO-World/assets/38314189/4ae76be0-b256-4cf1-8a78-94a9e7e6122d">

**Comment by KindredSpirithub** [comment]
Hi, I have a question, why the results of Zero-shot Evaluation on LVIS at readme are different with table2 in the paper? and if  i want finetune on the coco dataset to reproduce the results at the paper, can i use the checkpoint provided at the readme?

**Comment by wondervictor** [comment]
The results reported in Tab.2 are evaluated with `max_per_img=1000` and [fixed AP](https://github.com/achalddave/large-vocab-devil). The results in this repo are under the naive testing setting. Currently, the checkpoints in this repo will achieve higher results than the paper. As for fine-tuning, you can find more details in [configs/finetune_coco](https://github.com/AILab-CVC/YOLO-World/tree/master/configs/finetune_coco), and the checkpoints are from the huggingface links in the main README. BTW, we will update the fine-tuning settings in a day and obtain better fine-tuning results.

**Comment by wondervictor** [comment]
This issue will be closed since there is no further update related to the main topic. Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
