### ISSUE TITLE
关于在线demo

### ISSUE THREAD

**Issue by mingxingpu** [AILab-CVC/YOLO-World#193]
请问在线demo使用的是哪个权重呢？在哪里可以下载呢？

**Comment by mingxingpu** [comment]
@wondervictor 您好，我按照installation的说明：
1）新建了conda环境，接着clone  仓库到本地
2）cd YOLO-World，最后执行pip install -e .

运行image_demo.py的时候
config = './configs/pretrain/yolo_world_v2_l_clip_large_vlpan_bn_2e-3_100e_4x8gpus_obj365v1_goldg_train_800ft_lvis_minival.py'
checkpoint = './models/yolo_world_v2_l_clip_large_o365v1_goldg_pretrain_800ft-9df82e55.pth' 
报错，请问我该怎么解决呢？期待您的帮助，我将不胜感激！！
<img width="623" alt="error" src="https://github.com/AILab-CVC/YOLO-World/assets/59463530/bf14c1bb-8f65-4870-b51c-79315f737a78">

我使用pip list  查看了我的python环境，并导出了requirements.txt。可以看到我的python环境里是有yolo_world的
[requirements.txt](https://github.com/AILab-CVC/YOLO-World/files/14797263/requirements.txt)

**Comment by mingxingpu** [comment]
我重新配置了环境，现在可以成功import yolo_world。  但是我在尝试运行image_demo.py的过程中还是遇到了问题，

执行的命令为：
python image_demo.py ./configs/pretrain/yolo_world_v2_l_clip_large_vlpan_bn_2e-3_100e_4x8gpus_obj365v1_goldg_train_800ft_lvis_minival.py ../yoloworld/models/yolo_world_v2_l_clip_large_o365v1_goldg_pretrain_800ft-9df82e55.pth ../yoloworld/images/Clothing.jpg "clothing"  

报如下错误：
<img width="628" alt="mmcverror" src="https://github.com/AILab-CVC/YOLO-World/assets/59463530/a19be7dd-e167-4461-acf3-a9f362ed8802">


会不会是mmengine  mmcv  mmyolo  mmdet版本之间不适配的问题呢？我的mm系列库如下
<img width="200" alt="mmcv" src="https://github.com/AILab-CVC/YOLO-World/assets/59463530/972e1ecd-c20b-43e4-b306-628b9abbf5f5">

**Comment by scc103766** [comment]
> @wondervictor 您好，我按照installation的说明： 1）新建了conda环境，接着clone 仓库到本地 2）cd YOLO-World，最后执行pip install -e .
> 
> 运行image_demo.py的时候 config = './configs/pretrain/yolo_world_v2_l_clip_large_vlpan_bn_2e-3_100e_4x8gpus_obj365v1_goldg_train_800ft_lvis_minival.py' checkpoint = './models/yolo_world_v2_l_clip_large_o365v1_goldg_pretrain_800ft-9df82e55.pth' 报错，请问我该怎么解决呢？期待您的帮助，我将不胜感激！！ <img alt="error" width="623" src="https://private-user-images.githubusercontent.com/59463530/317920289-bf14c1bb-8f65-4870-b51c-79315f737a78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2OTgxNTIsIm5iZiI6MTcxMTY5Nzg1MiwicGF0aCI6Ii81OTQ2MzUzMC8zMTc5MjAyODktYmYxNGMxYmItOGY2NS00ODcwLWI1MWMtNzkzMTVmNzM3YTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA3MzczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZTI4YTVlMWQ1N2Q5MzhkZWJmZGRhNmFkMmQzNzY0ZWM2ZjZhOGI4MjgwZTQwMjA2MWRmODU3ODYwM2Y2MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B2cCjprgQK8WwsUOyTaOP44k8eRHkO-GkTA6Broks0M">
> 
> 我使用pip list 查看了我的python环境，并导出了requirements.txt。可以看到我的python环境里是有yolo_world的 [requirements.txt](https://github.com/AILab-CVC/YOLO-World/files/14797263/requirements.txt)

我也遇到了这个问题，请问你是怎么重新配置环境的呢

**Comment by wondervictor** [comment]
Hi @scc103766 @scc103766, 这个问题可以去掉config文件中的`file_client_args=_base_.file_client_args`

**Comment by auroraljg** [comment]
> 1）新建conda环境，python>=3.7。我选择的是python3.8。 2）使用pip安装torch。pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113 如果提示说由于xx包没有被安装，导致yy包没安装成功的话，就先用pip安装xx包，然后重新 pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113 3）pip install mmyolo==0.6.0;pip install install mmdet==3.0.0 如果遇到2）中同样的问题就按照同样的方式解决 4）git clone --递归 https://github.com/AILab-CVC/YOLO-World.git && cd YOLO-World 5）pip install -e .
> 
> 这样安装后可以进入python 然后导入yolo_world 不会报错。但是在运行image_demo.py的时候，会出现上面的第二个问题，不知道是不是openmmlab系列包之间不适配的问题。我也在等大佬 的回复。
Maybe you can change the MMCV version。
![image](https://github.com/AILab-CVC/YOLO-World/assets/103401092/d0cb8f54-f3bd-4f7f-bbf5-c67dd700605e)

**Comment by mingxingpu** [comment]
> > 1）新建conda环境，python>=3.7。我选择的是python3.8。 2）使用pip安装torch。pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113 如果提示说由于xx包没有被安装，导致yy包没安装成功的话，就先用pip安装xx包，然后重新 pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113 3）pip install mmyolo==0.6.0;pip install install mmdet==3.0.0 如果遇到2）中同样的问题就按照同样的方式解决 4）git clone --递归 https://github.com/AILab-CVC/YOLO-World.git && cd YOLO-World 5）pip install -e .
> > 这样安装后可以进入python 然后导入yolo_world 不会报错。但是在运行image_demo.py的时候，会出现上面的第二个问题，不知道是不是openmmlab系列包之间不适配的问题。我也在等大佬 的回复。
> > Maybe you can change the MMCV version。
> > ![image](https://private-user-images.githubusercontent.com/103401092/318628084-d0cb8f54-f3bd-4f7f-bbf5-c67dd700605e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNDI3ODAsIm5iZiI6MTcxMjA0MjQ4MCwicGF0aCI6Ii8xMDM0MDEwOTIvMzE4NjI4MDg0LWQwY2I4ZjU0LWYzYmQtNGY3Zi1iYmY1LWM2N2RkNzAwNjA1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMlQwNzIxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmExMGJkMWRiOTExZDJiZGY5MWI0NGM5NWNhODgwMWZkMzhhNWFkNzFhNGU2YWQ1OWMzY2QwOTY1ZDQxZjcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3PhoYmtJD0hniEvjoljGo22aSAQA8R_qm-HBRJ-4a6I)

Thanks for your suggestion. It works now.

**Comment by jiachen0212** [comment]
But there will be scale problems. Have you encountered them?

```
eturn F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (23x768 and 512x256)

```

**Comment by jiachen0212** [comment]
also you need change:

text_channels = 768  # 512

Otherwise, scaling errors will occur when running inference.

**Comment by pinecho** [comment]
1）conda create -n YOLO-World python=3.8。
2）pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113
3）pip install mmcv==2.0.0rc4; pip install mmyolo==0.6.0；pip install install mmdet==3.0.0 
4）git clone --recursive https://github.com/AILab-CVC/YOLO-World.git && cd YOLO-World
5）pip install -e .

That solved my problem, thanks!
