### ISSUE TITLE
Google Colab Notebook

### ISSUE THREAD

**Issue by yawarakaunagi** [AILab-CVC/YOLO-World#199]
When I run Colab Demo, I get the error RuntimeError: shape '[1, -1, 1203]' is invalid for input of size 518400. Do you know the cause?
![image](https://github.com/AILab-CVC/YOLO-World/assets/104401386/928304f1-10fb-454d-a94f-8412e8479df0)

**Comment by kommentlezz** [comment]
Happens to me too after pulling latest code

```
flatten_cls_scores = [
  File "/home/kafka/detection/YOLO-World/yolo_world/models/dense_heads/yolo_world_head.py", line 556, in <listcomp>
    cls_score.permute(0, 2, 3, 1).reshape(num_imgs, -1,
RuntimeError: shape '[1, -1, 1203]' is invalid for input of size 12800
```

**Comment by kommentlezz** [comment]
For the time being, you could switch to the working commit `git checkout 04954ffba51493c2ef99617434cd868273ad1350`

**Comment by AKholin** [comment]
> For the time being, you could switch to the working commit `git checkout 04954ffba51493c2ef99617434cd868273ad1350`

Thanks for the suggestion, I tried it, but still got the same error

**Comment by yawarakaunagi** [comment]
In my case it worked with git checkout 04954ffba51493c2ef99617434cd868273ad1350.
Thank you.
