### ISSUE TITLE
huggingface在国内被墙

### ISSUE THREAD

**Issue by 997897336** [AILab-CVC/YOLO-World#20]
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like pretrained_models/clip-vit-base-patch32-projection is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1402) of binary: /usr/bin/python

huggingface在国内被墙了，服务器没有代理，我想要下载下来放到服务器上利用本地文件加载，请问需要修改哪些内容

**Comment by QzYER** [comment]
> OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like pretrained_models/clip-vit-base-patch32-projection is not the path to a directory containing a file named config.json. Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'. ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1402) of binary: /usr/bin/python
> 
> huggingface在国内被墙了，服务器没有代理，我想要下载下来放到服务器上利用本地文件加载，请问需要修改哪些内容

镜像是个好东西。

**Comment by 997897336** [comment]
详聊一手

**Comment by 997897336** [comment]
https://github.com/AILab-CVC/YOLO-World/issues/20#issuecomment-1926270988哥们可以加个好友不，wx

**Comment by 997897336** [comment]
> > OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like pretrained_models/clip-vit-base-patch32-projection is not the path to a directory containing a file named config.json. Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'. ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1402) of binary: /usr/bin/python
> > huggingface在国内被墙了，服务器没有代理，我想要下载下来放到服务器上利用本地文件加载，请问需要修改哪些内容
> 
> 镜像是个好东西。

哥们加个wx好友不哈哈哈

**Comment by QzYER** [comment]
网址拿去


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AILab-CVC/YOLO-World"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月5日(星期一) 中午1:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AILab-CVC/YOLO-World] huggingface在国内被墙 (Issue #20)





   
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like pretrained_models/clip-vit-base-patch32-projection is not the path to a directory containing a file named config.json. Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'. ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1402) of binary: /usr/bin/python
 huggingface在国内被墙了，服务器没有代理，我想要下载下来放到服务器上利用本地文件加载，请问需要修改哪些内容
  
镜像是个好东西。
  
哥们加个wx好友不哈哈哈

**Comment by wondervictor** [comment]
Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.

**Comment by taofuyu** [comment]
> 到底放在哪个路径

YOLO-WORLD目录下建个文件夹pretrained_models。再翻墙把https://huggingface.co/openai/clip-vit-base-patch32/tree/main下载下来放进去即可

**Comment by SSTato** [comment]
> > 到底放在哪个路径
> 
> YOLO-WORLD目录下建个文件夹pretrained_models。再翻墙把[https://huggingface.co/openai/clip-vit-base-patch32/tree/main下载下来放进去即可](https://huggingface.co/openai/clip-vit-base-patch32/tree/main%E4%B8%8B%E8%BD%BD%E4%B8%8B%E6%9D%A5%E6%94%BE%E8%BF%9B%E5%8E%BB%E5%8D%B3%E5%8F%AF)

我已经下载下来了，但是还是不行，是哪里有问题
![image](https://github.com/AILab-CVC/YOLO-World/assets/93987794/64ca3bcc-f3d0-4f5f-a853-b64a83bdb458)

**Comment by wondervictor** [comment]
@SSTato 我的建议是，你先放到你自己的目录，然后修改config中的`model_name`为你放模型的本地路经。

**Comment by 997897336** [comment]
@wondervictor 老板说得对

**Comment by leo038** [comment]
please refer to: https://blog.csdn.net/leo0308/article/details/140505794?spm=1011.2415.3001.5331
