### ISSUE TITLE
RuntimeError: shape '[1, -1, 1203]' is invalid for input of size 12800

### ISSUE THREAD

**Issue by mingxingpu** [AILab-CVC/YOLO-World#202]
I pulled the latest codes 24c7121cf83c5808efef91c91b76277980feb99e, and ran the following command:
python image_demo.py \ 
./configs/pretrain/yolo_world_v2_x_vlpan_bn_2e-3_100e_4x8gpus_obj365v1_goldg_train_lvis_minival.py \ ../yoloworld/models/yolo_world_v2_x_obj365v1_goldg_cc3mlite_pretrain-8698fbfa.pth \
../yoloworld/images/Clothing.jpg \
"Clothing"

however, I got an error like this: 
  File "/root/project/pumingxing/zero_shot/YOLO-World/yolo_world/models/dense_heads/yolo_world_head.py", line 554, in predict_by_feat
    flatten_cls_scores = [
  File "/root/project/pumingxing/zero_shot/YOLO-World/yolo_world/models/dense_heads/yolo_world_head.py", line 555, in <listcomp>
    cls_score.permute(0, 2, 3, 1).reshape(num_imgs, -1,
RuntimeError: shape '[1, -1, 1203]' is invalid for input of size 12800

How can i fix this error?

**Comment by wondervictor** [comment]
I've checked this problem. You can now fix it by uncommenting:
https://github.com/AILab-CVC/YOLO-World/blob/24c7121cf83c5808efef91c91b76277980feb99e/yolo_world/models/detectors/yolo_world.py#L47

I'll push the correct version later.

**Comment by mingxingpu** [comment]
It works now, thanks for your help! @wondervictor

**Comment by wondervictor** [comment]
This issue will be closed since there is no further update related to the main topic. Besides, the error has been fixed already. Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
