### ISSUE TITLE
RuntimeError: shape '[1, -1, 1203]' is invalid for input of size 12800

### ISSUE THREAD

**Issue by zhujiajian98** [AILab-CVC/YOLO-World#203]
When I pull the newest demo of YOLO-World and use the image_demo.py to infer the image, it would arise the next error like this:
```text
Traceback (most recent call last):
  File "image_demo.py", line 196, in <module>
    inference_detector(runner,
  File "image_demo.py", line 85, in inference_detector
    output = runner.model.test_step(data_batch)[0]
  File "/opt/conda/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 145, in test_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "/opt/conda/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 361, in _run_forward
    results = self(**data, mode=mode)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 94, in forward
    return self.predict(inputs, data_samples)
  File "/home/zjj/project/YOLO-World/yolo_world/models/detectors/yolo_world.py", line 48, in predict
    results_list = self.bbox_head.predict(img_feats,
  File "/home/zjj/project/YOLO-World/yolo_world/models/dense_heads/yolo_world_head.py", line 324, in predict
    predictions = self.predict_by_feat(*outs,
  File "/home/zjj/project/YOLO-World/yolo_world/models/dense_heads/yolo_world_head.py", line 555, in predict_by_feat
    flatten_cls_scores = [
  File "/home/zjj/project/YOLO-World/yolo_world/models/dense_heads/yolo_world_head.py", line 556, in <listcomp>
    cls_score.permute(0, 2, 3, 1).reshape(num_imgs, -1,
RuntimeError: shape '[1, -1, 1203]' is invalid for input of size 12800
```

**Comment by zhujiajian98** [comment]
I check two issues of YOLO-World github repo, but we can't fix the error.

**Comment by mingxingpu** [comment]
@zhujiajian98   I ran into the same problem, and fixed the error.  maybe you can refer to https://github.com/AILab-CVC/YOLO-World/issues/202#issue-2217360202

**Comment by zhujiajian98** [comment]
@mingxingpu Thank you very much, but when I ran the image_demo.py, I still get the same error.
![Screenshot from 2024-04-02 10-33-44](https://github.com/AILab-CVC/YOLO-World/assets/66070217/0b0f9804-8728-4c6a-9261-c5e4a185497f)

**Comment by zhujiajian98** [comment]
The command I used is like this:
```shell
python image_demo.py configs/pretrain/yolo_world_v2_s_vlpan_bn_2e-3_100e_4x8gpus_obj365v1_goldg_train_lvis_minival.py /root/.cache/huggingface/hub/models--wondervictor--YOLO-World/snapshots/22efce1a2f6e751dfbf1626e9d039cb3b0f3e809/yolo_world_v2_s_obj365v1_goldg_pretrain-55b943ea.pth data/images/bus.jpg person,bus --topk 100
```

**Comment by mingxingpu** [comment]
> The command I used is like this:
> 
> ```shell
> python image_demo.py configs/pretrain/yolo_world_v2_s_vlpan_bn_2e-3_100e_4x8gpus_obj365v1_goldg_train_lvis_minival.py /root/.cache/huggingface/hub/models--wondervictor--YOLO-World/snapshots/22efce1a2f6e751dfbf1626e9d039cb3b0f3e809/yolo_world_v2_s_obj365v1_goldg_pretrain-55b943ea.pth data/images/bus.jpg person,bus --topk 100
> ```

you can try comment line 46  and uncomment line 47.

**Comment by mingxingpu** [comment]
> > The command I used is like this:
> > ```shell
> > python image_demo.py configs/pretrain/yolo_world_v2_s_vlpan_bn_2e-3_100e_4x8gpus_obj365v1_goldg_train_lvis_minival.py /root/.cache/huggingface/hub/models--wondervictor--YOLO-World/snapshots/22efce1a2f6e751dfbf1626e9d039cb3b0f3e809/yolo_world_v2_s_obj365v1_goldg_pretrain-55b943ea.pth data/images/bus.jpg person,bus --topk 100
> > ```
> 
> you can try comment line 46 and uncomment line 47.



> @mingxingpu Thank you very much, but when I ran the image_demo.py, I still get the same error. ![Screenshot from 2024-04-02 10-33-44](https://private-user-images.githubusercontent.com/66070217/318621355-0b0f9804-8728-4c6a-9261-c5e4a185497f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMzk3NjAsIm5iZiI6MTcxMjAzOTQ2MCwicGF0aCI6Ii82NjA3MDIxNy8zMTg2MjEzNTUtMGIwZjk4MDQtODcyOC00YzZhLTkyNjEtYzVlNGExODU0OTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA2MzEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1Nzk5YTY2MDZmODQ1NmVhMjMzMzA5OGZkMjM0Y2I0ODkzNjc3YTI1MGMxN2U1YmYyMjc5MjNhOWE1ODAyOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zOW-lUUtReWiD9TQh6TIzp3kvO0vXAF74AoC7f7ykxY)

you can try comment line 46  and uncomment line 47.

**Comment by zhujiajian98** [comment]
OK, thanks a lot. @mingxingpu
