### ISSUE TITLE
我来看看更新没有

### ISSUE THREAD

**Issue by QzYER** [AILab-CVC/YOLO-World#21]
![1707111850015](https://github.com/AILab-CVC/YOLO-World/assets/32487883/136d3018-928f-4cf3-9e4a-c83dcbd353c8)
一杯coffee 的时间到底有多长啊？

**Comment by wondervictor** [comment]
您好，非常感谢对于YOLO-World关注，我们正在进一步完善开源的代码和相应的社区，一直在更新的路上，我们将尽快完善各种部署的工具，提供微调的方案，以及更多更强的预训练模型。

**Comment by wondervictor** [comment]
Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
