### ISSUE TITLE
对于多类物体同时检测是否需要拆分类别？

### ISSUE THREAD

**Issue by RunsenXu** [AILab-CVC/YOLO-World#214]
您好，

我想请问一下假设我的待检测物体很多，比方说200类，那么使用yolo-world进行检测时，是这200类一次性一起输入进行检测性能比较高还是把这200类拆成多个组，比如说每组25类，然后再分别进行检测比较好呢？ 或者说没有区别？如果有的话，一组多少类比较合适呢？

期待您的解答，感谢！

**Comment by wondervictor** [comment]
如果说200类是不同的类别，不存在父类子类的问题，那放在一起检测效率会高且相对准确一些。如果存在父类子类混合的问题，最好是将父类和子类分开进行层次化处理，即先处理父类，后处理子类，其实可以修改一下模型获取object embeddings，然后根据类别去层次化匹配，找到最合适的类别，而不需要重复输入模型去推理。

**Comment by RunsenXu** [comment]
了解了，感谢！很高兴看到这样优秀的工作。

**Comment by kommentlezz** [comment]
> 如果说200类是不同的类别，不存在父类子类的问题，那放在一起检测效率会高且相对准确一些。如果存在父类子类混合的问题，最好是将父类和子类分开进行层次化处理，即先处理父类，后处理子类，其实可以修改一下模型获取object embeddings，然后根据类别去层次化匹配，找到最合适的类别，而不需要重复输入模型去推理。

怎么可以修改获取的embeddings 来做匹配？这里提到的“层次化匹配”大概是什么原理？

**Comment by wondervictor** [comment]
@kommentlezz 您好，这里的“层次化匹配”是指如果我有一个很大的类别树（表征父类-子类或从属类别）可以先从上层类别开始匹配，完成粗分类后，可以进一步和一些细分的类别进行匹配来确定更加细粒度的分类，这一过程有点类似于层次化的多分类。要实现这一过程，可以直接输出每个物体的embeddings，通过embeddings和预先构建的类别树实现这样的效果。

**Comment by kommentlezz** [comment]
@wondervictor 感谢您的解释！您可以推荐一些这种实现的代码仓或者论文吗，我想去多了解一下（因为我做的检查有6000多个类别）

**Comment by RunsenXu** [comment]
> @kommentlezz 您好，这里的“层次化匹配”是指如果我有一个很大的类别树（表征父类-子类或从属类别）可以先从上层类别开始匹配，完成粗分类后，可以进一步和一些细分的类别进行匹配来确定更加细粒度的分类，这一过程有点类似于层次化的多分类。要实现这一过程，可以直接输出每个物体的embeddings，通过embeddings和预先构建的类别树实现这样的效果。

感谢解释，我再思考了一下，其实把父类去掉，这样能保证父类和子类不冲突（同一个物体不会有多个class label），然后全部输入子类就可以了，也不需要先父类再子类了。

**Comment by wondervictor** [comment]
> @wondervictor 感谢您的解释！您可以推荐一些这种实现的代码仓或者论文吗，我想去多了解一下（因为我做的检查有6000多个类别）
@kommentlezz 目前暂时还没有，我们也正在做相关的实验在探索这个问题，如果后续有进展，我们会及时同步。

**Comment by Baboom-l** [comment]
@wondervictor 请教一下，yolo world里不是有图文融合吗，那怎么用类别树啊，文本不一样的时候，物体的embeddings也会变化啊
