### ISSUE TITLE
demo.py

### ISSUE THREAD

**Issue by Amas-Hu** [AILab-CVC/YOLO-World#219]
C:\Users\you\anaconda3\envs\yolo-world\python.exe C:\Files\PythonFiles\YOLO-World\demo.py 
Traceback (most recent call last):
  File "C:\Files\PythonFiles\YOLO-World\demo.py", line 26, in <module>
    from easydeploy import model as EM
ImportError: cannot import name 'model' from 'easydeploy' (C:\Users\you\anaconda3\envs\yolo-world\lib\site-packages\easydeploy\__init__.py)

**Comment by luosaidage** [comment]
我也是同样的问题

**Comment by c32155833** [comment]
我也遇到了。 是安装的easydeploy的版本不正确吗？
