### ISSUE TITLE
Improved visualisation of results with Supervision

### ISSUE THREAD

**Issue by SkalskiP** [AILab-CVC/YOLO-World#22]
Hi 👋🏻 First of all, I am very impressed with your model!

I noticed you have `supervision` in the dependency list, but I don't see it used in the code. I am the creator of this package. Would you be willing to accept a PR updating the visualization of the results? 

If you have any other ideas on how to use supervision, I am also very open to help.

**Comment by SkalskiP** [comment]
Here is an example result. We managed to plug supervision annotators into your `demo.py`.

![download - 2024-02-06T134821 471](https://github.com/AILab-CVC/YOLO-World/assets/26109316/89cc0cfa-9c63-4399-9afb-138e55254810)

**Comment by wondervictor** [comment]
Hi @SkalskiP, thank you for your kind interest in YOLO-World! Any PR that improves YOLO-World is welcomed😄! The visualizations with `Supervision` look wonderful!

**Comment by SkalskiP** [comment]
Hi @wondervictor 👋🏻 ! Awesome! Can we submit PR into your HF Space as well?

**Comment by wondervictor** [comment]
@SkalskiP, of course!

**Comment by SkalskiP** [comment]
@wondervictor I just opened HF Space PR: https://huggingface.co/spaces/stevengrove/YOLO-World/discussions/4

**Comment by wondervictor** [comment]
Hi @SkalskiP, done! Thank you!

**Comment by SkalskiP** [comment]
@wondervictor My pleasure! We would also like to YouTube a video about YOLO-World. Similar to the ones we did about:
- GroundingDINO - https://youtu.be/cMa77r3YrDk
- Segment Anything Model - https://youtu.be/D-D6ZmadzPE

Unfortunately, we will need to run YOLO-World in Colab to do this. We managed to do it, but the process was very difficult. Would you like us to do such a tutorial, and if so, can you help us streamline the installation in Colab?

**Comment by SkalskiP** [comment]
Hi @wondervictor 👋🏻 ! Is there any chance you could take a look at https://huggingface.co/spaces/stevengrove/YOLO-World/discussions/4 ?

**Comment by wondervictor** [comment]
This issue will be closed since there is no further update related to the main topic (or has been resolved). Thanks for your interest.  If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
