### ISSUE TITLE
pre-train datasets

### ISSUE THREAD

**Issue by pixiaopi2018** [AILab-CVC/YOLO-World#226]
Hello, in docs/data.md, it show that GQA has 621k images and Flickr has 149k images. But the downloaded datasets using the following links,  GQA has only 148k images and Flickr has only 31k images. Is there something wrong ?

**Comment by wondervictor** [comment]
Hi @pixiaopi2018, each image has several groups of annotations for GQA or Flickr. You can find more details by loading the annotation JSON files.

**Comment by pixiaopi2018** [comment]
Thanks, so the number, 148k and 31k are the same as your pre-training, right ?

**Comment by wondervictor** [comment]
Sure, the same images with different annotations are treated as different samples.
