### ISSUE TITLE
Have you tested the YOLOv8n model?

### ISSUE THREAD

**Issue by mjq2020** [AILab-CVC/YOLO-World#228]
I have tested your model and found it to be very effective, but my application scenario requires a smaller model, but I have not seen you disclose the pre-training weights of YOLOv8n. So I would like to ask if you have tested the effect of YOLOv8n. If so, what is the effect? Can you provide the pre-training weights of YOLOv8n? If not that's okay, we will train.

**Comment by wondervictor** [comment]
Hi @mjq2020, we have not pre-trained this nano-verison model yet. But we would like to add it to the plan to do it soon considering the nano-version model is necessary for the community!
