### ISSUE TITLE
The problem of train in custom dataset.

### ISSUE THREAD

**Issue by zhujiajian98** [AILab-CVC/YOLO-World#232]
According to the training process of the custom coco data set, I trained yolo-world to detect the custom data. The trained model has competitive performance with the yolo detector, but the open word detection capability has dropped to approximately zero. I found that yolo-world cannot detect other categories(even person). Can you tell me how to solve this problem? Thank you so much!

**Comment by zhujiajian98** [comment]
Would you tell me a better training scheme to train a yolo-world and keep the zero-shot detection ability?

**Comment by wondervictor** [comment]
Hi @zhujiajian98, finetuning all modules tends to hurt the zero-shot performance. To maintain the zero-shot ability, I suggest you fine-tuning with the GQA dataset.

**Comment by wondervictor** [comment]
In addition, better approaches for maintain the zero-shot ability are still under investigation.

**Comment by zhujiajian98** [comment]
@wondervictor But in fact, I just finetune yolo-world in my custom dataset by using the config file of `configs/finetune_coco/yolo_world_v2_l_vlpan_bn_sgd_1e-3_40e_8gpus_finetune_coco.py`. Do you mean I need to incorporate GQA into my custom dataset to complete finetune?

**Comment by wondervictor** [comment]
Yes, adding GQA will maintain the zero-shot ability which contains rich semantics. Currently, this is an effective approach to avoid catastrophic forgetting.

**Comment by zhujiajian98** [comment]
Ok, thank you for your reply, I will try to add the GQA dataset to my dataset to try training.

**Comment by wenqiuL** [comment]
@zhujiajian98 Hello, may I ask if there has been any improvement in zero sample performance since you joined the GQA dataset? Is there a significant difference in performance between the trained model and before you added it？
