### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv.image'

### ISSUE THREAD

**Issue by lizhiwen19900709** [AILab-CVC/YOLO-World#241]
mmcv 2.0.1
![image](https://github.com/AILab-CVC/YOLO-World/assets/15767823/610148f3-1be3-420b-8525-c59f8101f9b4)
![image](https://github.com/AILab-CVC/YOLO-World/assets/15767823/ba65376d-568a-486b-ade7-43c3428dfe1e)

**Comment by LYRgood** [comment]
你好 请问解决了吗
