### ISSUE TITLE
couldn't find pretrained_models/clip-vit-base-patch32-projection

### ISSUE THREAD

**Issue by lluo-Desktop** [AILab-CVC/YOLO-World#25]
Hi，
    In config : text model name is 'pretrained_models/clip-vit-base-patch32-projection'. 
    But I can't load tokenizer or clip_model by model name.
    I look into huggingface.co, can't find the model.
    Can you fix it ?

**Comment by xianshunw** [comment]
> Hi， In config : text model name is 'pretrained_models/clip-vit-base-patch32-projection'. But I can't load tokenizer or clip_model by model name. I look into huggingface.co, can't find the model. Can you fix it ?

same here, any suggestion?

**Comment by lluo-Desktop** [comment]
> > Hi， In config : text model name is 'pretrained_models/clip-vit-base-patch32-projection'. But I can't load tokenizer or clip_model by model name. I look into huggingface.co, can't find the model. Can you fix it ?
> 
> same here, any suggestion?

I use openAI CLIP_Vit as text encoder : https://huggingface.co/openai/clip-vit-base-patch32
It works.

**Comment by wingman-jr-addon** [comment]
@wondervictor @lluo-Desktop Any suggestions on an alternate model? I got the above one to work (thanks!), but the license is research-only and non-deployable, so it is more restrictive than the GPL license of this repository posing a barrier to any future deployment.

**Comment by onuralpszr** [comment]
@wingman-jr-addon maybe you can try https://github.com/mlfoundations/open_clip

**Comment by lluo-Desktop** [comment]
@onuralpszr @wingman-jr-addon 
Hi, my friends！Hvae you tired to train yolo-world on objects365/...  successfully?
I can't not reproduce the model.  Any suggestions?

**Comment by lluo-Desktop** [comment]
I see that the pretrian_model_name has been updated in newest config.
