### ISSUE TITLE
训练显存问题

### ISSUE THREAD

**Issue by Baboom-l** [AILab-CVC/YOLO-World#26]
请问一下你们在用mmyolo和mmdet训练yolo world模型的时候有没有遇到显存增长的问题。我使用mmdet中的rtmdet构建了类似方案，但训练时存在显存泄露，

**Comment by wondervictor** [comment]
您好，我们暂时没有发现显存递增的现象，是不是存在没有释放的tensor，或者会参与累计计算的tensor？

**Comment by Baboom-l** [comment]
mmengine有使用吗，相关版本能否提供。这个问题也可能是torch缓存的原因。

**Comment by wondervictor** [comment]
我们目前使用的环境是:
```
mmengine==0.10.2
mmcv==2.0.0
mmyolo=0.6.0
mmdetection==3.0.0
torch==1.13.1
```

**Comment by wondervictor** [comment]
Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
