### ISSUE TITLE
custom_imports的问题

### ISSUE THREAD

**Issue by zyf5988** [AILab-CVC/YOLO-World#266]
Traceback (most recent call last):
  File "tools/train.py", line 120, in <module>
    main()
  File "tools/train.py", line 59, in main
    cfg = Config.fromfile(args.config)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/config/config.py", line 476, in fromfile
    raise ImportError(err_msg) from e
ImportError: Failed to import custom modules from {'imports': ['yolo_world'], 'allow_failed_imports': False}, the current sys.path is: 
    /root/autodl-tmp/YOLO-World-master/tools
    /root/autodl-tmp/YOLO-World-master
    /root/miniconda3/lib/python38.zip
    /root/miniconda3/lib/python3.8
    /root/miniconda3/lib/python3.8/lib-dynload
    /root/miniconda3/lib/python3.8/site-packages
You should set `PYTHONPATH` to make `sys.path` include the directory which contains your custom module
按理来说第二个路径里就包含了yolo_world这个文件夹了呀，为什么还没法imports，有人有相同的问题吗

**Comment by robeson1010** [comment]
同样的问题

**Comment by the-cat-crying** [comment]
同样的问题
