### ISSUE TITLE
ImportError: Failed to import custom modules from {'imports': ['yolo_world'], 'allow_failed_imports': False}

### ISSUE THREAD

**Issue by robeson1010** [AILab-CVC/YOLO-World#267]
ImportError: Failed to import custom modules from {'imports': ['yolo_world'], 'allow_failed_imports': False}, the current sys.path is: 
    /opt/spark/python
    /opt/spark/python/lib/py4j-0.10.7-src.zip
    /home/staff/xin/Documents/YOLO-World
    /home/staff/xin/miniconda3/envs/YoloWord/lib/python38.zip
    /home/staff/xin/miniconda3/envs/YoloWord/lib/python3.8
    /home/staff/xin/miniconda3/envs/YoloWord/lib/python3.8/lib-dynload
    
    /home/staff/xin/miniconda3/envs/YoloWord/lib/python3.8/site-packages
    /tmp/tmpsyngbw_a
You should set `PYTHONPATH` to make `sys.path` include the directory which contains your custom module

**Comment by saminheydarian** [comment]
Did you find a solution?

**Comment by Dragosjosan** [comment]
Hi @robeson1010 @saminheydarian 

Try to add this line of code (in the import part of the module) the 'yolo_world' package:
´sys.path.append('/your_custom_path/yolo_world')´

**Comment by pinecho** [comment]
I encountered the same problem, adding "sys.path.append('/your_custom_path/yolo_world')" to the top of image_demo.py doesn't solve it.

**Comment by yomaesakura** [comment]
yolo_world中引用了transformers，如果你没有安装这个包，就无法导入，最搞的是报错不会报缺少transformers，而是会报在PYTHONPATH找不到包。所以pip install tranformers就可以了。
the yolo_world need to import transformers, but it won't be an error if you don't have it, and the error message show there isn't the package in PYTHONPATH.
so install transformers, then image demo can run

**Comment by Hikmat344** [comment]
ImportError: Failed to import custom modules from {'imports': ['projects.CO-DETR.codetr'], 'allow_failed_imports': False}, the current sys.path is:
...

You should set `PYTHONPATH` to make `sys.path` include the directory which contains your custom module

same issue I am facing

**Comment by tringuyen98** [comment]
any solution?

**Comment by shiboyang** [comment]
> any solution?

pip install transformers

**Comment by ztc20011103** [comment]
In the YOLO-World master directory, there's a directory called yolo-world which is the custom modules. Copy it into your PYTHONPATH, i.e. anaconda3\envs\(your envs name)\Lib\site-packages
