### ISSUE TITLE
coco zero-shot precision problem

### ISSUE THREAD

**Issue by gear106** [AILab-CVC/YOLO-World#288]
Hi, authors, I can't get the correct coco dataset mAP with the pretrained weight,  my test script is:
./tools/dist_test.sh  configs/finetune_coco/yolo_world_v2_l_vlpan_bn_sgd_1e-3_80e_8gpus_mask-refine_finetune_coco.py  pretrained_weight/yolo_world_v2_l_obj365v1_goldg_pretrain-a82b1fe3.pth

and the valdataset is  coco-val2017, use this test script I just get bbox_mAP_copypaste: 0.093 0.116 0.101 0.155 0.174 0.129,  What makes me feel strange is that the average precision is very low, but the average recall is relatively high, and the average recall(IoU=0.5:0.95 | area=all | maxDets=100) is about 0.558. 

how can I get the  correct zero-shot mAP use the dist_tesh.sh ? thks!

**Comment by gear106** [comment]
In my MMDET image, NMS was turned off by default. After adding NMS to the post-processing, the result was normal

**Comment by Niko000202** [comment]
May I ask where is the NMS setting? I couldn't find this parameter. Thanks!
