### ISSUE TITLE
Finetuning

### ISSUE THREAD

**Issue by slavkovsky77** [AILab-CVC/YOLO-World#30]
I know it only will be released but I would like to fine-tune this on a very small dataset.

I have two questions:

Is there any good example of how a dataset should look like? 
Is it possible to fine-tune it on a just one GPU with 40GB VRAM ?

**Comment by slavkovsky77** [comment]
Yeah, this link [fine-tuning configs](https://github.com/AILab-CVC/YOLO-World/issues/configs/finetune_coco/yolo_world_l_dual_vlpan_2e-4_80e_8gpus_finetune_coco.py) doesn't work :D 

but I am able to modify pre-training configs but it would be nice if you commit it.

**Comment by wondervictor** [comment]
Hi @slavkovsky77, we provide a simple guide for fine-tuning YOLO-World in [docs/fine-tuning](https://github.com/AILab-CVC/YOLO-World/blob/master/docs/finetuning.md). Hope it helps!

**Comment by slavkovsky77** [comment]
Why are there in this get compared to this?

https://huggingface.co/spaces/stevengrove/YOLO-World/tree/main

For example this is different

https://huggingface.co/spaces/stevengrove/YOLO-World/blob/main/yolo_world/models/detectors/yolo_world.py#L55
than here 

https://github.com/AILab-CVC/YOLO-World/blob/master/yolo_world/models/detectors/yolo_world.py

Which version is up to date? I would guess the demo is newer version

**Comment by wondervictor** [comment]
Hi @slavkovsky77, the HuggingFace version is an upcoming version and we will upload all pre-trained models soon. Currently, the GitHub version provides all weights of different scales. We suggest you use the GitHub version for downstream fine-tuning tasks or other applications.

**Comment by wondervictor** [comment]
BTW, the implementation of the GitHub version is consistent with the arXiv paper.

**Comment by wondervictor** [comment]
Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
