### ISSUE TITLE
TypeError: batch_data_samples should be dict or list

### ISSUE THREAD

**Issue by Lee-ray-a** [AILab-CVC/YOLO-World#301]
Hi, team, Great Works.

I am finetuning on my custom datasets, to get a powerful object detection model.

Currently, I am countering an error:
 
![image](https://github.com/AILab-CVC/YOLO-World/assets/71243853/882ff79b-817a-40b7-9da3-8ce7f939c0a5)

This is the code where it stopped:
![image](https://github.com/AILab-CVC/YOLO-World/assets/71243853/12c411ec-cabf-42c3-8f71-e922984d3c01)

This is ``batch_data_samples``:
![image](https://github.com/AILab-CVC/YOLO-World/assets/71243853/beb4aa85-1aca-4fe4-9b9d-280b506e5c73)

Where do I go wrong and cause this problem?
Thanks

**Comment by Lee-ray-a** [comment]
This is model config:
![image](https://github.com/AILab-CVC/YOLO-World/assets/71243853/b22eebee-7b19-4884-8eb2-476ecbdf26d6)

**Comment by mayfly508** [comment]
你解决了吗，我也遇到了这个问题
