### ISSUE TITLE
ONNX export not success

### ISSUE THREAD

**Issue by tycallen** [AILab-CVC/YOLO-World#305]
<img width="1967" alt="image" src="https://github.com/AILab-CVC/YOLO-World/assets/3022000/61feddb3-d7d7-4275-be9f-09ea37cb039f">
The convertion seems done, but the onnx file is kind of empty. Btw when will the tensorrt deploy release, appriciate your great work, thanks!

**Comment by clhne** [comment]
+1
解决了吗？

**Comment by clhne** [comment]
@wondervictor 天恒~ 这个帮忙看下呀，相同的导出命令，别的小伙伴可以，是不是和环境或者某些版本有关呢

**Comment by wondervictor** [comment]
@clhne 当然可以，这个我会尽快查一下，之前遇到过但没太注意。

**Comment by clhne** [comment]
解决了，加上 --model-only 就可以正常导出onnx模型了。
@tycallen 你可以试下。
@wondervictor check下export_onnx.py里面model_only 部分的代码逻辑是否有问题呢

**Comment by wondervictor** [comment]
@clhne `model-only`这部分是需要考虑后处理，这个我还没提供inference code，不过应该马上可以支持，我本地已经测完了不同的导出流程。

**Comment by clhne** [comment]
> @clhne `model-only`这部分是需要考虑后处理，这个我还没提供inference code，不过应该马上可以支持，我本地已经测完了不同的导出流程。

@wondervictor 上传下呗，正要对model-only进行inference

**Comment by clhne** [comment]
> @clhne 当然可以，这个我会尽快查一下，之前遇到过但没太注意。

这个查到哪里的bug了吗，还是需要导出带后处理的模型的

**Comment by clhne** [comment]
@wondervictor 
![image](https://github.com/AILab-CVC/YOLO-World/assets/11884005/82e778a8-d64e-4c0e-9e58-9c354155158e)
如图，上面截图是不加--model-only的，为啥
`deploy_model(fake_input)     # dry run`
这个跑完是空的呢？

**Comment by wondervictor** [comment]
@clhne 可以尝试一下使用 `--without-nms`, 目前我们这块提供了支持，不推荐使用`--model-only`.

**Comment by wondervictor** [comment]
如果需要量化模型，我们推荐使用`--without-bbox-decoder`。更多信息请查看：https://github.com/AILab-CVC/YOLO-World/blob/master/docs/deploy.md#export-yolo-world-to-onnx-models
