### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by bf-yang** [AILab-CVC/YOLO-World#323]
I've tried: PYTHONPATH=./ python demo/simple_demo.py
and: PYTHONPATH=/home/bufang/YOLO-World python demo/simple_demo.py 

But they both have errors:
FileNotFoundError: [Errno 2] No such file or directory: '/home/bufang/YOLO-World/configs/pretrain/../../third_party/mmyolo/configs/yolov8/yolov8_x_syncbn_fast_8xb16-500e_coco.py'

**Comment by lvke9529** [comment]
You can check out this blog post：
https://blog.csdn.net/ITdaka/article/details/138863017?spm=1001.2014.3001.5501

**Comment by bf-yang** [comment]
The README of this Repo is so helpful, and this repo is very easy to deploy, what a good work it is~

**Comment by wondervictor** [comment]
This issue will be closed since there is no further update related to the main topic. Besides, the error has been fixed already. Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
