### ISSUE TITLE
ERROR: No matching distribution found for opencv-python-headless==4.2.0.34

### ISSUE THREAD

**Issue by XieKaiwen** [AILab-CVC/YOLO-World#345]
Tried installing the requirements file using pip, but there is no matching distribution apparently. 

ERROR: Could not find a version that satisfies the requirement opencv-python-headless==4.2.0.34 (from versions: 3.4.10.37, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.15.55, 3.4.16.59, 3.4.17.61, 3.4.17.63, 3.4.18.65, 4.3.0.38, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.3.56, 4.5.4.58, 4.5.4.60, 4.5.5.62, 4.5.5.64, 4.6.0.66, 4.7.0.68, 4.7.0.72, 4.8.0.74, 4.8.0.76, 4.8.1.78, 4.9.0.80)
ERROR: No matching distribution found for opencv-python-headless==4.2.0.34

Please recommend which version do I switch to

**Comment by wondervictor** [comment]
Hi, you can install:

```bash
pip install opencv-python-headless --upgrade
pip install opencv-python --upgrade
```
