### ISSUE TITLE
FileNotFoundError with demo.py

### ISSUE THREAD

**Issue by NitheshRajmohan** [AILab-CVC/YOLO-World#35]
Ran into a bit of trouble trying to get the demo running with one of the finetune_coco configs. I'm getting a FileNotFoundError when I run the demo script. Looks like it's missing a file from the mmyolo configs.

- Cloned the repo and set everything up as per the instructions.
- Tried running the demo with this command:
``` 
python demo.py YOLO-World-master/configs/finetune_coco/yolo_world_l_dual_vlpan_2e-4_80e_8gpus_finetune_coco.py YOLO-World-master/yolo_world_l_clip_base_dual_vlpan_2e-3adamw_32xb16_100e_o365_goldg_train_pretrained-0e566235.pth 
```
- And hit this error:
```
FileNotFoundError: [Errno 2] No such file or directory: 'YOLO-World-master/configs/finetune_coco/../../third_party/mmyolo/configs/yolov8/yolov8_l_mask-refine_syncbn_fast_8xb16-500e_coco.py'
```
Any ideas on what's going on or how to fix this? Would really appreciate the help!

Thanks!

**Comment by Highfly1212** [comment]
I added the folder third_party into the repository and then just cloned the mmyolo (https://github.com/open-mmlab/mmyolo) repository into the folder.

**Comment by NitheshRajmohan** [comment]
Thanks a bunch!
