### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'configs/pretrain/yolo_world_v2_x_vlpan_bn_2e-3_100e_4x8gpus_obj365v1_goldg_train_1280ft_lvis_minival.py'

### ISSUE THREAD

**Issue by toutua** [AILab-CVC/YOLO-World#356]
Hello,  my CUDA version is 11.8 and Torch version is 2.0.1, I encountered an error when trying to run the simple_demo.py file, stating "FileNotFoundError: [Errno 2] No such file or directory: 'configs/pretrain/yolo_world_v2_x_vlpan_bn_2e-3_100e_4x8gpus_obj365v1_goldg_train_1280ft_lvis_minival.py''". However, upon checking the file path, I found that the file does exist on my computer. How can I resolve this issue? Your help is greatly appreciated.

**Comment by wondervictor** [comment]
see: https://github.com/AILab-CVC/YOLO-World/blob/master/configs/pretrain/yolo_world_v2_x_vlpan_bn_2e-3_100e_4x8gpus_obj365v1_goldg_train_1280ft_lvis_minival.py

**Comment by toutua** [comment]
Thank you for your response. I eventually found that it was a file path issue. I resolved the problem by modifying the path to "config_file = "../configs/pretrain/yolo_world_v2_x_vlpan_bn_2e-3_100e_4x8gpus_obj365v1_goldg_train_1280ft_lvis_minival.py"."

**Comment by wondervictor** [comment]
This issue will be closed since there is no further update related to the main topic. Besides, the error has been fixed already. Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
