### ISSUE TITLE
哪位大神帮我看看 按照大家的步骤来的 我真的不知道哪里出错了 。。。。。。。

### ISSUE THREAD

**Issue by 1012537710** [AILab-CVC/YOLO-World#366]
-------------------------------------------我的模型配置是这样的（在官方下载的COCO数据集）：------------------------------------------
_base_ = (
    '../../third_party/mmyolo/configs/yolov8/'
    'yolov8_s_syncbn_fast_8xb16-500e_coco.py')
custom_imports = dict(
    imports=['yolo_world'],
    allow_failed_imports=False)

# hyper-parameters
num_classes = 80
num_training_classes = 80
max_epochs = 80  # Maximum training epochs
close_mosaic_epochs = 10
save_epoch_intervals = 5
text_channels = 512
neck_embed_channels = [128, 256, _base_.last_stage_out_channels // 2]
neck_num_heads = [4, 8, _base_.last_stage_out_channels // 2 // 32]
base_lr = 2e-4
weight_decay = 0.05
train_batch_size_per_gpu = 2 #16
# load_from='pretrained_models/yolo_world_l_clip_base_dual_vlpan_2e-3adamw_32xb16_100e_o365_goldg_train_pretrained-0e566235.pth'
load_from = '/root/YePeng/YOLO-World-master/pretrained_models/yolo_world_s_clip_base_dual_vlpan_2e-3adamw_32xb16_100e_o365_goldg_train_pretrained-18bea4d2.pth'
persistent_workers = False  # False

# model settings
model = dict(
    type='YOLOWorldDetector',
    mm_neck=True,
    num_train_classes=num_training_classes,
    num_test_classes=num_classes,
    data_preprocessor=dict(type='YOLOWDetDataPreprocessor'),
    backbone=dict(
        _delete_=True,
        type='MultiModalYOLOBackbone',
        image_model={{_base_.model.backbone}},
        text_model=dict(
            type='HuggingCLIPLanguageBackbone',
            model_name='openai/clip-vit-base-patch32',
            frozen_modules=['all'])),
    neck=dict(type='YOLOWorldDualPAFPN',
              guide_channels=text_channels,
              embed_channels=neck_embed_channels,
              num_heads=neck_num_heads,
              block_cfg=dict(type='MaxSigmoidCSPLayerWithTwoConv'),
              text_enhancder=dict(type='ImagePoolingAttentionModule',
                                  embed_channels=256,
                                  num_heads=8)),
    bbox_head=dict(type='YOLOWorldHead',
                   head_module=dict(type='YOLOWorldHeadModule',
                                    embed_dims=text_channels,
                                    num_classes=num_training_classes)),
    train_cfg=dict(assigner=dict(num_classes=num_training_classes)))

# dataset settings
text_transform = [
    dict(type='RandomLoadText',
         num_neg_samples=(num_classes, num_classes),
         max_num_samples=num_training_classes,
         padding_to_max=True,
         padding_value=''),
    dict(type='mmdet.PackDetInputs',
         meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape', 'flip',
                    'flip_direction', 'texts'))
]
mosaic_affine_transform = [
    dict(
        type='MultiModalMosaic',
        img_scale=_base_.img_scale,
        pad_val=114.0,
        pre_transform=_base_.pre_transform),
    dict(
        type='YOLOv5RandomAffine',
        max_rotate_degree=0.0,
        max_shear_degree=0.0,
        max_aspect_ratio=100.,
        scaling_ratio_range=(1 - _base_.affine_scale,
                             1 + _base_.affine_scale),
        # img_scale is (width, height)
        border=(-_base_.img_scale[0] // 2, -_base_.img_scale[1] // 2),
        border_val=(114, 114, 114))
]
train_pipeline = [
    *_base_.pre_transform,
    *mosaic_affine_transform,
    dict(
        type='YOLOv5MultiModalMixUp',
        prob=_base_.mixup_prob,
        pre_transform=[*_base_.pre_transform,
                       *mosaic_affine_transform]),
    *_base_.last_transform[:-1],
    *text_transform
]
train_pipeline_stage2 = [
    *_base_.train_pipeline_stage2[:-1],
    *text_transform
]
coco_train_dataset = dict(
    _delete_=True,
    type='MultiModalDataset',
    dataset=dict(
        type='YOLOv5CocoDataset',
        data_root='/root/YePeng/YOLO-World-master/data/coco',
        ann_file='/root/YePeng/YOLO-World-master/data/coco/annotations/instances_train2017.json',
        data_prefix=dict(img='/root/YePeng/YOLO-World-master/data/coco/train2017/'),
        filter_cfg=dict(filter_empty_gt=False, min_size=32)),
    class_text_path='/root/YePeng/YOLO-World-master/data/texts/coco_class_texts.json',
    pipeline=train_pipeline)

train_dataloader = dict(
    persistent_workers=persistent_workers,
    batch_size=train_batch_size_per_gpu,
    collate_fn=dict(type='yolow_collate'),
    dataset=coco_train_dataset)
test_pipeline = [
    *_base_.test_pipeline[:-1],
    dict(type='LoadText'),
    dict(
        type='mmdet.PackDetInputs',
        meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape',
                   'scale_factor', 'pad_param', 'texts'))
]
coco_val_dataset = dict(
    _delete_=True,
    type='MultiModalDataset',
    dataset=dict(
        type='YOLOv5CocoDataset',
        data_root='/root/YePeng/YOLO-World-master/data/coco',
        ann_file='/root/YePeng/YOLO-World-master/data/coco/annotations/instances_val2017.json',
        data_prefix=dict(img='/root/YePeng/YOLO-World-master/data/coco/val2017/'),
        filter_cfg=dict(filter_empty_gt=False, min_size=32)),
    class_text_path='/root/YePeng/YOLO-World-master/data/texts/coco_class_texts.json',
    pipeline=test_pipeline)
val_dataloader = dict(dataset=coco_val_dataset)
test_dataloader = val_dataloader
# training settings
default_hooks = dict(
    param_scheduler=dict(
        scheduler_type='linear',
        lr_factor=0.01,
        max_epochs=max_epochs),
    checkpoint=dict(
        max_keep_ckpts=-1,
        save_best=None,
        interval=save_epoch_intervals))
custom_hooks = [
    dict(
        type='EMAHook',
        ema_type='ExpMomentumEMA',
        momentum=0.0001,
        update_buffers=True,
        strict_load=False,
        priority=49),
    dict(
        type='mmdet.PipelineSwitchHook',
        switch_epoch=max_epochs - close_mosaic_epochs,
        switch_pipeline=train_pipeline_stage2)
]
train_cfg = dict(
    max_epochs=max_epochs,
    val_interval=5,
    dynamic_intervals=[((max_epochs - close_mosaic_epochs),
                        _base_.val_interval_stage2)])
optim_wrapper = dict(
    optimizer=dict(
        _delete_=True,
        type='AdamW',
        lr=base_lr,
        weight_decay=weight_decay,
        batch_size_per_gpu=train_batch_size_per_gpu),
    paramwise_cfg=dict(
        custom_keys={'backbone.text_model': dict(lr_mult=0.01),
                     'logit_scale': dict(weight_decay=0.0)}),
    constructor='YOLOWv5OptimizerConstructor')

# evaluation settings
val_evaluator = dict(
    _delete_=True,
    type='mmdet.CocoMetric',
    proposal_nums=(100, 1, 10),
    ann_file='/root/YePeng/YOLO-World-master/data/coco/annotations/instances_val2017.json',
    metric='bbox')

--------------------------------------------------------------BUG如下：-------------------------------------
loading annotations into memory...
Done (t=17.97s)
creating index...
index created!
/root/miniconda3/envs/yolosam/lib/python3.9/site-packages/albumentations/core/composition.py:144: UserWarning: Got processor for bboxes, but no transform to process it.
  self._set_keys()
05/30 14:13:15 - mmengine - INFO - paramwise_options -- bbox_head.head_module.cls_contrasts.0.logit_scale:lr=0.0002
05/30 14:13:15 - mmengine - INFO - paramwise_options -- bbox_head.head_module.cls_contrasts.0.logit_scale:weight_decay=0.0
05/30 14:13:15 - mmengine - INFO - paramwise_options -- bbox_head.head_module.cls_contrasts.1.logit_scale:lr=0.0002
05/30 14:13:15 - mmengine - INFO - paramwise_options -- bbox_head.head_module.cls_contrasts.1.logit_scale:weight_decay=0.0
05/30 14:13:15 - mmengine - INFO - paramwise_options -- bbox_head.head_module.cls_contrasts.2.logit_scale:lr=0.0002
05/30 14:13:15 - mmengine - INFO - paramwise_options -- bbox_head.head_module.cls_contrasts.2.logit_scale:weight_decay=0.0
loading annotations into memory...
Done (t=0.66s)
creating index...
index created!
loading annotations into memory...
Done (t=0.68s)
creating index...
index created!
Loads checkpoint by local backend from path: ./pretrained_models/yolo_world_s_clip_base_dual_vlpan_2e-3adamw_32xb16_100e_o365_goldg_train_pretrained-18bea4d2.pth
05/30 14:13:21 - mmengine - INFO - Load checkpoint from ./pretrained_models/yolo_world_s_clip_base_dual_vlpan_2e-3adamw_32xb16_100e_o365_goldg_train_pretrained-18bea4d2.pth
05/30 14:13:21 - mmengine - WARNING - "FileClient" will be deprecated in future. Please use io functions in https://mmengine.readthedocs.io/en/latest/api/fileio.html#file-io
05/30 14:13:21 - mmengine - WARNING - "HardDiskBackend" is the alias of "LocalBackend" and the former will be deprecated in future.
05/30 14:13:21 - mmengine - INFO - Checkpoints will be saved to /root/YePeng/YOLO-World-master/work_dirs/yolo_world_s_dual_vlpan_2e-4_80e_8gpus_finetune_coco.
Traceback (most recent call last):
  File "/root/YePeng/YOLO-World-master/./tools/train.py", line 120, in <module>
    main()
  File "/root/YePeng/YOLO-World-master/./tools/train.py", line 116, in main
    runner.train()
  File "/root/miniconda3/envs/yolosam/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1777, in train
    model = self.train_loop.run()  # type: ignore
  File "/root/miniconda3/envs/yolosam/lib/python3.9/site-packages/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/root/miniconda3/envs/yolosam/lib/python3.9/site-packages/mmengine/runner/loops.py", line 111, in run_epoch
    for idx, data_batch in enumerate(self.dataloader):
  File "/root/miniconda3/envs/yolosam/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/yolosam/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/envs/yolosam/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/root/miniconda3/envs/yolosam/lib/python3.9/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/envs/yolosam/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/envs/yolosam/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/yolosam/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/YePeng/YOLO-World-master/yolo_world/datasets/mm_dataset.py", line 86, in __getitem__
    return self.pipeline(data_info)
  File "/root/miniconda3/envs/yolosam/lib/python3.9/site-packages/mmengine/dataset/base_dataset.py", line 60, in __call__
    data = t(data)
  File "/root/miniconda3/envs/yolosam/lib/python3.9/site-packages/mmcv/transforms/base.py", line 12, in __call__
    return self.transform(results)
  File "/root/miniconda3/envs/yolosam/lib/python3.9/site-packages/mmdet/structures/bbox/box_type.py", line 267, in wrapper
    return func(self, results)
  File "/root/miniconda3/envs/yolosam/lib/python3.9/site-packages/mmdet/datasets/transforms/transforms.py", line 1507, in transform
    results = self.aug(**results)
  File "/root/miniconda3/envs/yolosam/lib/python3.9/site-packages/albumentations/core/composition.py", line 255, in __call__
    self._check_args(**data)
  File "/root/miniconda3/envs/yolosam/lib/python3.9/site-packages/albumentations/core/composition.py", line 324, in _check_args
    raise ValueError(msg)
ValueError: Key img_path is not in available keys.
说的是数据集加载有错，但是我实在是不知道哪里出错了。我检查了好几遍数据集的路径，都没啥问题。哪位大神帮我看看，感谢大家了。

**Comment by wondervictor** [comment]
```bash
pip install albumentations==1.4.4
```

**Comment by 1012537710** [comment]
@wondervictor 大哥，牛逼，运行起来了。非常感谢大哥。

**Comment by andynnnnn** [comment]
> @wondervictor 大哥，牛逼，运行起来了。非常感谢大哥。
兄弟，按照你的代码跑完流程，能达到多少mAP，我目前第二个epoch，loss下降就慢下来了
