### ISSUE TITLE
测试结果惨不忍睹

### ISSUE THREAD

**Issue by ByronGe** [AILab-CVC/YOLO-World#368]
根本没有宣传那么牛逼，比起Grounding DINO差了十万八千里，费时费力跑通程序，不要骗人了

**Comment by wondervictor** [comment]
请提供使用的模型，命令，以及测试样例。

**Comment by wondervictor** [comment]
@ByronGe please refer to https://github.com/AILab-CVC/YOLO-World/issues/108.

**Comment by ByronGe** [comment]
![bus](https://github.com/AILab-CVC/YOLO-World/assets/29230326/b8aa09de-b5d8-4c10-9424-0eea5d82e961)
[MP24010547-问题清单1.docx](https://github.com/user-attachments/files/15508810/MP24010547-.1.docx)
![zidane](https://github.com/AILab-CVC/YOLO-World/assets/29230326/c0afbc73-f1d3-4165-9f09-cbdd39f8021c)
![screenshots](https://github.com/AILab-CVC/YOLO-World/assets/29230326/cdc4459c-d6d7-4f65-a2d6-839a5d5168f1)

**Comment by ByronGe** [comment]
@wondervictor 我测试了官方提供的两张图片，使用image_demo.py脚本，text="eye,head,face,hand,person,clothes"，效果如上两张图片。

**Comment by wondervictor** [comment]
![image](https://github.com/AILab-CVC/YOLO-World/assets/15026693/c3c04ab4-5f18-4341-b7e0-e78ed215ca93)

**Comment by wondervictor** [comment]
![image (1)](https://github.com/AILab-CVC/YOLO-World/assets/15026693/d1c087b6-a55f-432f-b833-e5144664623f)

**Comment by wondervictor** [comment]
以上来自HF demo结果，maxdets=100，threshold=0.01，nms=0.5，目前版本YOLO-World的确出现置信度偏低的问题，但不至于很多东西detect不出来。

**Comment by ByronGe** [comment]
当前版本中给出的置信度是0.1，我设置成0.01后的确能检测出很多，但同样误检也有不少。
你给出的两张图片有的head能检测出来，有的没有，有的clothes能检测出来，有的没有。。。。
在实际使用中设置这么低吗，这两张都是官方的图片，自己的图片效果只会更加不理想。

**Comment by wondervictor** [comment]
关于你的问题：
1. 首先，我们使用时，会去依据实际情况设置threshold，YOLO-World本身就依赖于较低的threshold，这个问题我们在之前的issues有讨论过，是一个在优化的点。
2. 其次，并不保证所有prompt都能稳定检出。
3. 在我给的样例结果中，clothes没检测出来是因为我们为了demo可视化，额外增加了class-agnostic NMS，clothes和person的IoU较高，导致会被抑制掉。实际使用中可以去掉这个class-agnostic NMS，尤其是评测或者需要更高精度的检测结果。
4. 这的确是提供的样例，但所有prompts由用户提供，我们完全可以为了可视化效果去提供一些参考的prompt。

关于你最初的问题：
1. 十万八千里是多少，我们的实验对比没有失去偏颇，在这里，我们希望能提供quantitative or qualitative comparisons来衡量“十万八千里”。
2. 我们提供了所有代码和模型，所有结果公开透明，不少工作已经基于YOLO-World做了很多应用，我们在何时何地“骗人”。

**Comment by ByronGe** [comment]
1：首先，我是根据官方默认的数值，threshold=0.1,官方的图片进行测试，但实际效果是非常不好。
2：其次，我设置的prompt也不是很刁难人，就很难普通的，那我想说，就那两张图片，提供一下你那边可视化结果好的prompt。
3：所谓的十万八千里只是一直直观的说法，别的模型结果好，你给出的模型结果不好，我这么形容罢了，至于具体的数值多少，这毕竟很麻烦。

**Comment by wondervictor** [comment]
1. 这就是一个默认数值，我们也强烈建议过大家尝试不同的threshold。
2. 我只是提出，prompt会影响实际结果，具体怎么选看需求，看任务。
3. 首先，数值我们已经帮你量化好了，你需要我可以提供给你。我觉得大家要为自己的话负责，十万八千里我们得有一个量化指标去对应吧，或者你给出你认为Grounding DINO好的点。其次，你觉得谁好就用谁。
4. 最后，我不明白什么叫做“不要骗人了”，我们所有东西全都公开透明，数据、模型、参数、训练测试。

声明：我们欢迎大家交流问题，你可以带着“踩一捧一”的态度批判与指责，但我们希望所有的评价都是基于公平、统一、公正的条件。

**Comment by ByronGe** [comment]
1：正常来讲，yolo的阈值一般是0.25，然后0.01的确有点低，我没尝试过。
2：我看很多人都在用这个模型，但是基本没人提出这个问题，就是image_demo测试好坏。
3：你可以感性的理解一下我的话，十万八千里，不要骗人了也好，就是对测试结果的不满意。
4：你们东西公开透明，这个是论文需要，但是我们在使用过程当中，只需要一个好的结果。
5：你一直说prompt很重要，那我还是那句话，在那两张图上，给几个你认为好的prompt。
声明，我当然希望你们的yoloworld好，乃至跟yolo一样，我的评价只是依据一个普通的测试结果。

**Comment by wondervictor** [comment]
1. 我们本身的setting就和普通YOLO不一致，训练测试都是有差异的，包括threshold的设置，这个问题我觉得更偏向于实际，不同需求不同任务的threshold确实不一样。
2. 至于置信度这个问题，有不少active/inactive issues讨论过这个问题，我们也直面这个问题，也在的确优化这个东西。
3. 按照大众的做法，论文不需要公开透明，毕竟大量论文并不会开源代码，更不会给你讨论技术细节。我们出于想做好这件事，追求公开透明，你实际需求需要好结果，我完全理解，大家都有这样的追求，那我们更希望是针对现在的问题去讨论解决方案。
4. 至于prompt, 直接可视化COCO zeroshot结果：

<img width="1519" alt="截屏2024-05-31 16 04 03" src="https://github.com/AILab-CVC/YOLO-World/assets/15026693/917e7d24-f641-4b9d-9a49-2a62bd7c7e2e">

![image (2)](https://github.com/AILab-CVC/YOLO-World/assets/15026693/68c9cc8a-5c85-4ffe-9b2c-50532c80f5a9)

**Comment by ByronGe** [comment]
好的，麻烦你了这么长时间。
还有就是为什么你前后两个结果不一样，前一个置信度都很低，这个就好了很多

**Comment by wondervictor** [comment]
我们目前有多个模型可以尝试，所以会有一些差距吧，本地demo和云端demo的模型也不一样。

另外，我们天然支持zero-shot grounding/referring，能够提供一些基础的grounding能力。

<img width="1103" alt="截屏2024-05-31 16 25 59" src="https://github.com/AILab-CVC/YOLO-World/assets/15026693/06ea648b-302f-4b1c-971f-0e68233a8f81">

**Comment by sunjian2015** [comment]
> 关于你的问题：
> 
> 1. 首先，我们使用时，会去依据实际情况设置threshold，YOLO-World本身就依赖于较低的threshold，这个问题我们在之前的issues有讨论过，是一个在优化的点。
> 2. 其次，并不保证所有prompt都能稳定检出。
> 3. 在我给的样例结果中，clothes没检测出来是因为我们为了demo可视化，额外增加了class-agnostic NMS，clothes和person的IoU较高，导致会被抑制掉。实际使用中可以去掉这个class-agnostic NMS，尤其是评测或者需要更高精度的检测结果。
> 4. 这的确是提供的样例，但所有prompts由用户提供，我们完全可以为了可视化效果去提供一些参考的prompt。
> 
> 关于你最初的问题：
> 
> 1. 十万八千里是多少，我们的实验对比没有失去偏颇，在这里，我们希望能提供quantitative or qualitative comparisons来衡量“十万八千里”。
> 2. 我们提供了所有代码和模型，所有结果公开透明，不少工作已经基于YOLO-World做了很多应用，我们在何时何地“骗人”。

您好，请问，nms 是在哪里做的啊？demo 的代码里没有看到，还需要拿到结果后再做一遍 nms 吗？

**Comment by weilanShi** [comment]
> 1：首先，我是根据官方默认的数值，threshold=0.1,官方的图片进行测试，但实际效果是非常不好。 2：其次，我设置的prompt也不是很刁难人，就很难普通的，那我想说，就那两张图片，提供一下你那边可视化结果好的prompt。 3：所谓的十万八千里只是一直直观的说法，别的模型结果好，你给出的模型结果不好，我这么形容罢了，至于具体的数值多少，这毕竟很麻烦。

image_demo.py 推理有问题，你转onnx, 推理，结果还是很好的//

![Image](https://github.com/user-attachments/assets/f3371f4b-717c-42dd-962c-65b8c7c3cade)
