### ISSUE TITLE
CC3M pretrain data

### ISSUE THREAD

**Issue by gear106** [AILab-CVC/YOLO-World#375]
great work!
how to use MixedGroundingDataset to load CC3M pretrain data, the CC3M image-text data  annotations doesn't has 'tokens_positive' as MixedGroundingDataset defined,  if I want to use CC3M box level text tokens annotation to train the pretrained model, how to load this dataset, can the authors give some examples ? 

thks again!

**Comment by gear106** [comment]
@wondervictor Thank you for your reply, did the the DATASET CLASS for CC3M updated for now? I haven't find any update file in main repository,

**Comment by wondervictor** [comment]
done, please see: https://github.com/AILab-CVC/YOLO-World/blob/b449b98202e931590513c16e4830318be2dde946/configs/pretrain/yolo_world_v2_x_vlpan_bn_2e-3_100e_4x8gpus_obj365v1_goldg_cc3mlite_train_lvis_minival.py#L103

**Comment by gear106** [comment]
> done, please see:
> 
> https://github.com/AILab-CVC/YOLO-World/blob/b449b98202e931590513c16e4830318be2dde946/configs/pretrain/yolo_world_v2_x_vlpan_bn_2e-3_100e_4x8gpus_obj365v1_goldg_cc3mlite_train_lvis_minival.py#L103

@wondervictor thank you, you've really helped me a lot
