### ISSUE TITLE
Segmentation results

### ISSUE THREAD

**Issue by Gary-code** [AILab-CVC/YOLO-World#40]
Could the demo output the segmentation results rather than the detection bounding box

**Comment by wondervictor** [comment]
Hi @Gary-code, we'll provide the segmentation code and models soon.

**Comment by wondervictor** [comment]
Hi @Gary-code, we've released the code & models for open-vocabulary instance segmentation. We have built a simple **YOLO-World-Seg** and leverage a simple fine-tuning of the segmentation model on the `LVIS-base`. We currently provide an initial version, and we will provide a stronger segmentation weights in the future.

**Comment by wondervictor** [comment]
Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
