### ISSUE TITLE
ImportError: Failed to import custom modules from {'imports': ['yolo_world'], 'allow_failed_imports': False}

### ISSUE THREAD

**Issue by mohammadmirzaee25** [AILab-CVC/YOLO-World#403]
Hi. 
I am using your demo model . I tried using your google colab note book and your github code.
i get this error in this line:
    cfg = Config.fromfile(
        "/content/YOLO-World/configs/pretrain/yolo_world_l_t2i_bn_2e-4_100e_4x8gpus_obj365v1_goldg_train_lvis_minival.py"
    )
error is :
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory
During handling of the above exception, another exception occurred:
ImportError                               Traceback (most recent call last)
ImportError: Failed to import yolo_world

ImportError: Failed to import custom modules from {'imports': ['yolo_world'], 'allow_failed_imports': False}, the current sys.path is: 
    /content
    /env/python
    /usr/lib/python310.zip
    /usr/lib/python3.10
    /usr/lib/python3.10/lib-dynload
    
    /usr/local/lib/python3.10/dist-packages
    /usr/lib/python3/dist-packages
    /usr/local/lib/python3.10/dist-packages/IPython/extensions
    /root/.ipython
    /tmp/tmpzoiunxqh
You should set `PYTHONPATH` to make `sys.path` include the directory which contains your custom module

Can you Help me please?

**Comment by mansi104-ai** [comment]
Hi, I was encountering the same error, but checkout this page :
https://github.com/AILab-CVC/YOLO-World/blob/master/docs/installation.md

there was some error with the installation with installation with openmim , which was later resolved by running this command :
!mim install mmcv==2.0.0

**Comment by mohammadmirzaee25** [comment]
Hi @mansi104-ai , Thanks for answering .
I had tried !mim install mmcv==2.0.0 . but it didnt work
now i found out i should change my torch version
!pip install torch==2.0.0 torchvision==0.15.1 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu118 
now it works. Thanks a lot.

**Comment by wenqianlv** [comment]
将系统提示的路径加入系统路径，即可解决

**Comment by shiboyang** [comment]
pip install transformers

**Comment by tringuyen98** [comment]
pip install -e . (you must install pyproject.toml file)

**Comment by PuppetDiary** [comment]
In my case, except add "export PYTHONPATH=/root/YOLO-World/yolo_world" to environment in console, I alse add "export PATHONPATH=/root/YOLO-World" which solved my issue. So, we need both of path ~/YOLO-World and ~/yolo_world in PYTHONPATH.
