### ISSUE TITLE
Inference on test image

### ISSUE THREAD

**Issue by jmartinez-beh** [AILab-CVC/YOLO-World#41]
Is there a sample inference script on a test image?
With NMS, number of boxes, and text parameters?

**Comment by wondervictor** [comment]
Hi @jmartinez-beh, we provide a new [`image-demo`](https://github.com/AILab-CVC/YOLO-World?tab=readme-ov-file#image-demo) for a test image now, you can have a try~

**Comment by wondervictor** [comment]
Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
