### ISSUE TITLE
image_demo.py

### ISSUE THREAD

**Issue by guanning03** [AILab-CVC/YOLO-World#432]
where can I find the config file? Suppose I am using the [YOLO-Worldv2-X]

The following is the code in `./demo/image_demo.py`

![image](https://github.com/user-attachments/assets/613fabd5-45a9-4f26-8fd8-e58898f6a2e2)

**Comment by lvke9529** [comment]
参考一下是否对你有帮助：https://blog.csdn.net/ITdaka/article/details/139306984

**Comment by guanning03** [comment]
好的，谢谢您
