### ISSUE TITLE
config file 

### ISSUE THREAD

**Issue by HeChengHui** [AILab-CVC/YOLO-World#46]
I am able to run the new model with CC3M-lite using the 2 yolo_world_l config files. Is there supposed to be a new config file for this new model or which of the 2 am i suppose to run?

**Comment by wondervictor** [comment]
Hi @HeChengHui, the pre-trained checkpoints with CC3M-Lite can be used to infer with any one of the two L configs. This checkpoint of YOLO-World-L is pre-trained with O365+GoldG+CC3M-Lite while the model is the same. Later, we will provide the annotations files of CC3M.
