### ISSUE TITLE
got error while install mmcv library

### ISSUE THREAD

**Issue by sceddd** [AILab-CVC/YOLO-World#473]
This repository require mmcv==2.0.0rc4,<2.1.0 and I tried to download it but end up with error, what is the real version of mmcv in your repo?

**Comment by import-jalashwa** [comment]
You can disable the assertions in the __init__.py file of the mmdet, I ran it with mmcv version 2.2.0, haven't faced any issues

**Comment by sceddd** [comment]
any better idea for this issue instead of remove that line? I tryna replicate this repository so I need the correct one for learning about this models

**Comment by wondervictor** [comment]
Hi @sceddd, you could install an earlier version such as 2.0.0 / 2.1.0. We provide several ways to install mmcv in: https://github.com/AILab-CVC/YOLO-World/blob/master/docs/installation.md#install-mmcv
