### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by sssssshf** [AILab-CVC/YOLO-World#493]
运行 命令如下

chmod +x tools/dist_train.sh
./tools/dist_train.sh configs/pretrain/train.py 1 --amp

训练报错
![image](https://github.com/user-attachments/assets/6c47cb86-d2a1-432c-b491-d15096a3484d)

**Comment by imatif17** [comment]
Hi!

Did you fix this?

**Comment by M3Dade** [comment]
@imatif17  different --local-rank  between  --local_rank
