### ISSUE TITLE
 How can I modify the code to make YoloWorld detect any object in an image?

### ISSUE THREAD

**Issue by YeahTOT** [AILab-CVC/YOLO-World#498]
How can I modify the code to make YoloWorld detect any object in an image?

**Comment by FantasticZihao** [comment]
> How can I modify the code to make YoloWorld detect any object in an image?

have you figured it out? if figured, can you give me some instructions?

**Comment by YeahTOT** [comment]
No, I intend to use it for anomaly object detection (where any unmarked objects are considered anomalies), but I haven't found an effective way to modify it based on YoloWorld. Using two-stage models is too slow. If you have any good ideas, I'd love to discuss them together.


> > How can I modify the code to make YoloWorld detect any object in an image?
> 
> have you figured it out? if figured, can you give me some instructions?

**Comment by FantasticZihao** [comment]
> 不，我打算将其用于异常对象检测（其中任何未标记的对象都被视为异常），但我还没有找到基于 YoloWorld 对其进行修改的有效方法。使用两阶段模型太慢。如果你有什么好主意，我很乐意一起讨论。
> 
> > > How can I modify the code to make YoloWorld detect any object in an image?
> > 
> > 
> > have you figured it out? if figured, can you give me some instructions?

I wondered that if you changed you cuda version into 11.8 to adapt to the requirement when deploying the project.
