### ISSUE TITLE
image_demo.py

### ISSUE THREAD

**Issue by sczlmy** [AILab-CVC/YOLO-World#53]
I have a problem when running image_demo.py

Loads checkpoint by local backend from path: yolo_world_l_clip_base_dual_vlpan_2e-3adamw_32xb16_100e_o365_goldg_cc3mlite_train_pretrained-7a5eea3b.pth
02/16 23:06:23 - mmengine - INFO - Load checkpoint from yolo_world_l_clip_base_dual_vlpan_2e-3adamw_32xb16_100e_o365_goldg_cc3mlite_train_pretrained-7a5eea3b.pth
[                                                  ] 0/1, elapsed: 0s, ETA:/home/kemove/anaconda3/envs/YOLO_World/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "image_demo.py", line 154, in <module>
    inference_detector(runner,
  File "image_demo.py", line 78, in inference_detector
    pred_instances.scores.float() > score_thr]
TypeError: '>' not supported between instances of 'Tensor' and 'str'

**Comment by wingman-jr-addon** [comment]
I ran into this too - looks like the thresholds weren't cast to numbers. Just made this mod at the end:
```
    for image_path in images:

        inference_detector(runner,
                           image_path,
                           texts,
                           float(args.topk),
                           float(args.threshold),
                           output_dir=output_dir,
                           use_amp=args.amp,
                           show=args.show)
        progress_bar.update()
```

**Comment by wingman-jr-addon** [comment]
Looks like this got fixed recently, see e.g. https://github.com/AILab-CVC/YOLO-World/blob/master/image_demo.py#L31

**Comment by sczlmy** [comment]
@wingman-jr-addon Thank you for your explanation, I have successfully run it, but there seems to be some issue with the results.
![cat_dog](https://github.com/AILab-CVC/YOLO-World/assets/91841386/57e31ba9-8f4b-42aa-88e1-a62ad419cd67)

**Comment by sczlmy** [comment]
@wingman-jr-addon Thank you for your explanation, I have successfully run it.

**Comment by wondervictor** [comment]
Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
