### ISSUE TITLE
issue about prompt in demo

### ISSUE THREAD

**Issue by ztc20011103** [AILab-CVC/YOLO-World#539]
请问对于一个多名词的prompt，我用一个逗号隔开每一个名词，为什么最后识别的结果会出现两个prompt连在一起的label，这是模型处理prompt的结果吗？具体来说，我正在对一个celebrity数据集做inference，当输入如“lebron james, lionel messi, taylor swift”的prompt，有时候会出现lebron james lionel的label。

**Comment by hosee16** [comment]
> 请问对于一个多名词的prompt，我用一个逗号隔开每一个名词，为什么最后识别的结果会出现两个prompt连在一起的label，这是模型处理prompt的结果吗？具体来说，我正在对一个celebrity数据集做inference，当输入如“lebron james, lionel messi, taylor swift”的prompt，有时候会出现lebron james lionel的label。

请问您是如何解决的呢，可否分享一下解决方法
