### ISSUE TITLE
change texts in demo.py web ui, can't work.

### ISSUE THREAD

**Issue by nxdong** [AILab-CVC/YOLO-World#58]
texts on gradio web ui only work once, but restart the server cant work correctly.  
I wonder if it's a mechanism,
or is there a way to reset the runner status to load new texts prompt ?

![yoloworld](https://github.com/AILab-CVC/YOLO-World/assets/6704315/9d91219c-8262-4d97-ad23-d09a3645c73f)

**Comment by wondervictor** [comment]
Hi @nxdong and @cainiaoqiuxue, I apologize for the late late late reply. This problem has been fixed now and you can have a try along with exporting ONNX models.

**Comment by wondervictor** [comment]
This issue will be closed since there is no further update related to the main topic. Besides, the error has been fixed already. Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
