### ISSUE TITLE
How to extract object nouns from caption?

### ISSUE THREAD

**Issue by myhz0606** [AILab-CVC/YOLO-World#60]
From your paper, you propose a module used to extract object nouns from captions provided by the user. It's very interesting, but I have not found this processor in your demo. Can you provide it? 
Thanks very much.

**Comment by lxfater** [comment]
If I have to input a large number of detection categories (1000), will this affect performance? @wondervictor

**Comment by wondervictor** [comment]
Hi @lxfater, it will not affect and YOLO-World is born for custom vocabularies without re-training.

**Comment by lxfater** [comment]
If I feed 5,000 words into the model as categories and ask it to recognize any image, does that cause a performance problem compared to categories that only appear in the image? I'm a novice in this field @wondervictor

**Comment by wondervictor** [comment]
Hi @lxfater, generally, this will not have an impact, unless there are some similar categories or hard-to-distinguish categories among the 5000 words.

**Comment by wondervictor** [comment]
Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.

**Comment by wondervictor** [comment]
Hi @tuotalimiaomiao, sure. But I strongly suggest you use the pre-trained weights to initialize, which is very useful.
