### ISSUE TITLE
how to transfer this model to iOS? Is there some tutorial to do that?

### ISSUE THREAD

**Issue by qihuijia** [AILab-CVC/YOLO-World#63]

**Comment by StevenGrove** [comment]
Currently, we do not have a direct tutorial for iOS devices. But you can utilize our huggingface demo to export the ONNX model. Following that, you may attempt to deploy it on your device using a platform-aware framework, such as NCNN.

**Comment by qihuijia** [comment]
Thanks very much. Because right now, the coremltools do not support onnx to coreml, it support to convert pytorch to coreml directly. So I will try this approach

**Comment by qihuijia** [comment]
I found a not very perfect solution:
```python
import torch
from ultralytics import YOLO  # Assuming you have Ultralytics installed

with torch.no_grad():
    # Initialize a YOLO-World model
    model = YOLO("yolov8s-world.pt")  # or select yolov8m/l-world.pt
    model.export(format="coreml", nms=True)

    print("Model exported successfully to custom_yolov8s.mlpackage for CoreML inference!")
```

But I can not set the classes what I want.
