### ISSUE TITLE
Error finetuning yolo world KeyError: 'texts'

### ISSUE THREAD

**Issue by pribadihcr** [AILab-CVC/YOLO-World#64]
Hi, I got the following error when finetuning yolo world. Thanks

```
YOLO-World/yolo_world/models/data_preprocessors/data_preprocessor.py", line 58, in forward
    'texts': data_samples['texts'],
KeyError: 'texts'
```

**Comment by wondervictor** [comment]
Hi @pribadihcr, have you added the text json file or text to the box? Please refer to [fine-tuning](https://github.com/AILab-CVC/YOLO-World/blob/master/docs/data.md#dataset-class).

**Comment by wondervictor** [comment]
This issue will be closed since there is no further update related to the main topic. Thanks for your interest.  If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
