### ISSUE TITLE
微调过程中的一个警告

### ISSUE THREAD

**Issue by 997897336** [AILab-CVC/YOLO-World#68]
​​![4d5eae90-2b53-441d-b52c-8fd202e8a658](https://github.com/AILab-CVC/YOLO-World/assets/78671643/fda5dcf3-e9b6-4d94-941d-773ebd938b09)
这个警告会不会造成什么影响？

**Comment by wondervictor** [comment]
您好，这个警告没有任何影响，请放心使用。
