### ISSUE TITLE
如何导出基于EfficientCSPLayerWithTwoConv结构的onnx模型结构？

### ISSUE THREAD

**Issue by David-19940718** [AILab-CVC/YOLO-World#69]
希望能提供一个导出流程和对应的ort_demo示例。

**Comment by wondervictor** [comment]
@David-19940718  ONNX和TensorRT目前正在测试过程中，马上会更新。

**Comment by CVHub520** [comment]
> @David-19940718 ONNX和TensorRT目前正在测试过程中，马上会更新。

非常感谢！期待好消息，如果能打通下游部署，能极大提升该工作的价值！

**Comment by David-19940718** [comment]
> @David-19940718 ONNX和TensorRT目前正在测试过程中，马上会更新。

hello，请问这个计划什么时间会发布？

**Comment by LuletterSoul** [comment]
> > @David-19940718 ONNX和TensorRT目前正在测试过程中，马上会更新。
> 
> hello，请问这个计划什么时间会发布？

同样需要，因为里面含有特殊的算子，ONNX导出失败，想学习本项目是怎么处理这种问题的。

**Comment by Hongyuan-Liu** [comment]
期待尽快发布

**Comment by wondervictor** [comment]
@Hongyuan-Liu @LuletterSoul @David-19940718 各位好，我们目前更新了一版YOLO-World，目前提供了ONNX和TensorRT的转换code，目前在一个BETA版本，欢迎大家使用和测试，如果有问题可以即时反馈，也欢迎大家帮忙改进和改善！

**Comment by David-19940718** [comment]
> @Hongyuan-Liu @LuletterSoul @David-19940718 各位好，我们目前更新了一版YOLO-World，目前提供了ONNX和TensorRT的转换code，目前在一个BETA版本，欢迎大家使用和测试，如果有问题可以即时反馈，也欢迎大家帮忙改进和改善！

同问。另外请问这个转换code是只支持v2版本的模型还是v1和v2均可？

**Comment by LuletterSoul** [comment]
> > > @Hongyuan-Liu @LuletterSoul @David-19940718 各位好，我们目前更新了一版YOLO-World，目前提供了ONNX和TensorRT的转换code，目前在一个BETA版本，欢迎大家使用和测试，如果有问题可以即时反馈，也欢迎大家帮忙改进和改善！
> > > where is the code？new branch？
> 
> @jzx-gooner check it in `./deploy`
> 
> > > @Hongyuan-Liu @LuletterSoul @David-19940718 各位好，我们目前更新了一版YOLO-World，目前提供了ONNX和TensorRT的转换code，目前在一个BETA版本，欢迎大家使用和测试，如果有问题可以即时反馈，也欢迎大家帮忙改进和改善！
> > 
> > 
> > 同问。另外请问这个转换code是只支持v2版本的模型还是v1和v2均可？
> 
> @David-19940718 原理上都是支持的，但是现在v2转换后的效率会更高。

![image](https://github.com/AILab-CVC/YOLO-World/assets/21377419/c31fc4e9-2763-409c-b8fb-72362b53f793)
关于部署阶段的T-CSPLayer重参数化我不是很理解，txt_feats是一个[1, 1203, 4, 32]的向量，怎么可以变成一个1*1的Conv呢？

**Comment by wondervictor** [comment]
@LuletterSoul 您好，这里是分成了4个group，每一个group里面都是一个1x1的conv。

**Comment by QzYER** [comment]
> @Hongyuan-Liu @LuletterSoul @David-19940718 各位好，我们目前更新了一版YOLO-World，目前提供了ONNX和TensorRT的转换code，目前在一个BETA版本，欢迎大家使用和测试，如果有问题可以即时反馈，也欢迎大家帮忙改进和改善！

你好，现在利用deploy.py无法成功转出onnx或者trt。请问和mmyolo、mmdeploy、mmengine、mmcv的版本有关系嘛？你们的版本是怎样的？现在无法降微调之后的pth转成onnx。按理说tokenzier是无法转为onnx的。

**Comment by wondervictor** [comment]
Hi @Hongyuan-Liu, @jzx-gooner, @xiyangyang99, @LuletterSoul, @David-19940718, you can export the ONNX model through the `demo.py` now. More tools for exporting models will come in these days.

**Comment by wondervictor** [comment]
This issue will be closed since there is no further update related to the main topic. Besides, the error has been fixed already. Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
