### ISSUE TITLE
如何微调出适合自己的数据集？

### ISSUE THREAD

**Issue by Ggggfgjjjk** [AILab-CVC/YOLO-World#7]
作者你好，一项十分出色的工作！太牛了！想请教您如何在预训练模型的基础上去微调出适合自己的模型？简单来说是，使用少量的数据进行微调，然后利用微调出的模型去标注类似大量的数据

**Comment by wondervictor** [comment]
您好，非常感谢您对YOLO-World的关注，我们目前已经公开了代码和预训练的权重，对于微调，可以加载我们预训练模型来作为初始化权重，并使用较小的learning rate训练(推荐2e-4)，我们将在近期(两天内)公开在COCO/LVIS微调的配置文件，以及custom数据集的构建方式，到时候可以作为参考，欢迎持续关注！

**Comment by qpfhuan** [comment]
> 您好，非常感谢您对YOLO-World的关注，我们目前已经公开了代码和预训练的权重，对于微调，可以加载我们预训练模型来作为初始化权重，并使用较小的learning rate训练(推荐2e-4)，我们将在近期(两天内)公开在COCO/LVIS微调的配置文件，以及custom数据集的构建方式，到时候可以作为参考，欢迎持续关注！

太牛了！！！请问，除了微调训练，在text prompt上有什么建议吗？

**Comment by QzYER** [comment]
> 您好，非常感谢您对YOLO-World的关注，我们目前已经公开了代码和预训练的权重，对于微调，可以加载我们预训练模型来作为初始化权重，并使用较小的learning rate训练(推荐2e-4)，我们将在近期(两天内)公开在COCO/LVIS微调的配置文件，以及custom数据集的构建方式，到时候可以作为参考，欢迎持续关注！

作者你好，你们的离线词汇的方式是什么啊？是文本和图像分开的吗？groundingdino因为交叉注意力的计算不得不同时进行，yolo-world好像感觉是推理的时候直接将训练好之后的词汇权重或者参数直接拿过来用，是clip的那种方式吗？

**Comment by wondervictor** [comment]
@qpfhuan 您好，我们目前提供了一些关于fine-tuning的细节以及相应的config，在COCO和LVIS的权重我们也将快速上传，您可以参考 [docs/fine-tuning](https://github.com/AILab-CVC/YOLO-World/blob/master/docs/finetuning.md)这个介绍在自己的数据集上尝试一下，如果有不清楚的地方，欢迎讨论！

**Comment by bobo0810** [comment]
@wondervictor 您好，麻烦问下  基于下游的闭集检测数据微调后是否还保留原来的泛化性呢？

**Comment by doing123456-be** [comment]
> @bobo0810 您好，fine-tuning会影响pre-train的zero-shot性能（包括泛化性），但不代表fine-tuning完后模型不再具备zero-shot能力。可以根据fine-tuning的数据量和fine-tuning的迭代数可以控制这个影响，如果可以的话，我比较推荐尝试fine-tuning后面head部分的layers，或者尝试引入LoRA。这一块我们目前还没有做很多的探索，后续我们也会尝试用LoRA做fine-tuning，如果有新的结论，我们会及时更新本repo，在此感谢您的关注！

请问LoRA微调的实验有比较好的结果吗，加在哪些层效果较好，是否会开源相关代码 @wondervictor

**Comment by xsank** [comment]
> > [@bobo0810](https://github.com/bobo0810) 您好，fine-tuning会影响pre-train的zero-shot性能（包括泛化性），但不代表fine-tuning完后模型不再具备zero-shot能力。可以根据fine-tuning的数据量和fine-tuning的迭代数可以控制这个影响，如果可以的话，我比较推荐尝试fine-tuning后面head部分的layers，或者尝试引入LoRA。这一块我们目前还没有做很多的探索，后续我们也会尝试用LoRA做fine-tuning，如果有新的结论，我们会及时更新本repo，在此感谢您的关注！
> 
> 请问LoRA微调的实验有比较好的结果吗，加在哪些层效果较好，是否会开源相关代码 [@wondervictor](https://github.com/wondervictor)

同样很感兴趣！ @wondervictor 请问有相关进展不？
