### ISSUE TITLE
Can you give me the config file of yolo-world about image_demo.py?

### ISSUE THREAD

**Issue by zhujiajian98** [AILab-CVC/YOLO-World#70]
I have read your image_demo.py, but the config file should be given into the example file.

**Comment by partheee** [comment]
https://github.com/AILab-CVC/YOLO-World/tree/master/configs
Check this !

**Comment by wondervictor** [comment]
Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
