### ISSUE TITLE
question about fine-tuning and open-vocabulary

### ISSUE THREAD

**Issue by taofuyu** [AILab-CVC/YOLO-World#71]
For example,  I use own dataset to fine-tune YOLO-World for close-set object detection (only two classes: car  person) using MultiModalDataset with a text json ([['car'], ['person']]). Then I use trained model to inference a picture with prompt 'dog', but the dog in this picture can not be detected, I'm confused about 'open-vocabulary' and 'zero-shot' in this situation.
Thanks for amazing work!

**Comment by wondervictor** [comment]
Hi @taofuyu, thanks for your interest!
1. YOLO-World has the zero-shot open-vocabulary detection ability, which can detect objects beyond the training vocabulary or training corpus. Such as, after training on the seen categories (e.g., person, cat), the model can generalize to unseen categories, e.g., dog.
2. Fine-tuning YOLO-World on your custom datasets will affect the zero-shot ability, but it may not affect too much.
3. You can adjust the `threshold` to see whether the dog is detected or not.

`open-vocabulary`: model trained on the `seen` categories can generalize to `unseen` categories.
