### ISSUE TITLE
很赞的工作&与detic的比较

### ISSUE THREAD

**Issue by jzx-gooner** [AILab-CVC/YOLO-World#8]
感谢作者，这是一项很赞的工作！！！我想从detect everything的角度上来使用这个模型，所以选取了同一张测试图片，与detic做了推理上的比较,有两个问题：
1.yolo-world的检测confidence会稍微有些低，但这不影响使用
2.yolo-world在这张图片上检出率会稍微差一些，是因为detic是大模型的缘故？
![ceshi2](https://github.com/AILab-CVC/YOLO-World/assets/29942202/5bb6d96d-29cd-4fd8-8ff0-46b2d7519374)
and i use 'cone' world  set confidence to 0.01
![image](https://github.com/AILab-CVC/YOLO-World/assets/29942202/f348df76-0a92-46e9-bcb5-43acb0d846aa)

![image](https://github.com/AILab-CVC/YOLO-World/assets/29942202/98baf164-9b5e-4258-8614-7e5147eb9d0e)
![image](https://github.com/AILab-CVC/YOLO-World/assets/29942202/3c1836d7-93fa-4c79-b763-ea8195ec1d5e)

**Comment by wondervictor** [comment]
@jzx-gooner 您好，非常感谢对YOLO-World的关注！YOLO-World的confidence一方面是文本与区域的匹配相似度，另一方面还包含了框的精度（IoU-aware），因此可能导致分数会偏低，另一方面，我们的demo中提供了额外的NMS，使用demo的时候可以提高NMS的IoU阈值，这样漏检的结果会稍微少一些，其次，目前YOLO-World支持的分辨率是640x640，相比Detic应该小了一些，导致在small objects上效果不如detic，不过我们后续会提供更高分辨率的预训练模型，到时候欢迎帮忙体验和测试一下❤️
