### ISSUE TITLE
关于MultiModalDataset

### ISSUE THREAD

**Issue by nhw649** [AILab-CVC/YOLO-World#82]
作者，您好。请问对于同义词你是怎么处理的呢？像ODISE、FC-CLIP的做法是在预测的时候进行max ensemble，但是这样的操作特别耗时，会影响FPS。
例如，num_templates存储的是每个类别的同义词个数，它会将每个类别的所有同义词模板进行max操作，这样得到的final_pred_logits维度为[B, N, num_classes]
```
cur_idx = 0
for num_t in num_templates:
    final_pred_logits.append(pred_logits[:, :, cur_idx: cur_idx + num_t].max(-1).values)
    cur_idx += num_t
```

**Comment by wondervictor** [comment]
@nhw649，您好，我们目前没有特别处理同义词或者定义一组prompt templates然后融合分数。目前还是维持了一个简单高效的方式，直接用用户输入的text，不增加额外的prompt，也不做融合。

**Comment by wondervictor** [comment]
This issue will be closed since there is no further update related to the main topic. Thanks for your interest.  If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
