### ISSUE TITLE
Ques about the evaluation results

### ISSUE THREAD

**Issue by tengyunlai** [AILab-CVC/YOLO-World#88]
There are 2 evaluation matrix in the README doc, which are val_fixed and val_mini. May I ask whether the results obtained after pre-training using the default configuration(located in configs/pretrain/yolo_world_m_dual_vlpan_l2norm_2e-3_100e_4x8gpus_obj365v1_goldg_train_lvis_minival.py) in the code are fixed or mini.

My result after training is shown below, which is not the same as proposed in the README doc.
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=300 catIds=all] = 0.301
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=300 catIds=all] = 0.394
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=300 catIds=all] = 0.323
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=     s | maxDets=300 catIds=all] = 0.191
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=     m | maxDets=300 catIds=all] = 0.389
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=     l | maxDets=300 catIds=all] = 0.545
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=300 catIds=  r] = 0.210
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=300 catIds=  c] = 0.279
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=300 catIds=  f] = 0.336
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=300 catIds=all] = 0.394
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=     s | maxDets=300 catIds=all] = 0.229
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=     m | maxDets=300 catIds=all] = 0.481
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=     l | maxDets=300 catIds=all] = 0.687
02/26 15:49:02 - mmengine - INFO - Epoch(val) [100][602/602]    lvis/bbox_AP: 0.3010  lvis/bbox_AP50: 0.3940  lvis/bbox_AP75: 0.3230  lvis/bbox_APs: 0.1910  lvis/bbox_APm: 0.3890  lvis/bbox_APl: 0.5450  lvis/bbox_APr: 0.2100  lvis/bbox_APc: 0.2790  lvis/bbox_APf: 0.3360  data_time: 0.0003  time: 0.1913

**Comment by wondervictor** [comment]
Hi @tengyunlai, the results evaluated by the framework (mmyolo/mmdetection) are normal. If you are interested in the `fixed AP`, you need to save the `json results` by adding `--json-prefix` and increase the number of detections `--cfg-options model.test_cfg.max_per_img=1000` during testing. And you need to install the [large-vocab-devil](https://github.com/achalddave/large-vocab-devil) tools for evaluating the `fixed AP`.

**Comment by tengyunlai** [comment]
ok. so it means that my val result is better than yours. hh
