### ISSUE TITLE
预训练权重无法下载

### ISSUE THREAD

**Issue by 997897336** [AILab-CVC/YOLO-World#9]
![15974884-cc4d-4c11-bbf5-25827b996477](https://github.com/AILab-CVC/YOLO-World/assets/78671643/175356d4-7257-472a-b32e-148ecefe6fa4)
预训练权重下载出现这个问题，请问怎么解决？

**Comment by wondervictor** [comment]
@997897336 您好，这个问题应该已经解决，您可以再试试。

**Comment by wondervictor** [comment]
Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
