### ISSUE TITLE
Training curves

### ISSUE THREAD

**Issue by NatanBagrov** [AILab-CVC/YOLO-World#93]
Hello and thanks for the awesome work on the paper and sharing the code!

Is it possible for you to share TB (or logs) to see training curves, for the pre-trainings and fine-tuning, to check reproduction?

Thanks

**Comment by wondervictor** [comment]
@NatanBagrov, sure, but I need some time to organize and plan to release tomorrow.

**Comment by wondervictor** [comment]
Hi @NatanBagrov, we have already updated the pre-training logs now.
