### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'class_id'

### ISSUE THREAD

**Issue by Limbicnation** [AILab-CVC/YOLO-World#94]
When running inference, using the command: `python image_demo.py ` .`/configs/finetune_coco/yolo_world_l_dual_vlpan_2e-4_80e_8gpus_finetune_coco.py /../YOLO-World/weights/yolo_world_seg_l_dual_vlpan_2e-4_80e_8gpus_allmodules_finetune_lvis-8c58c916.pth /../YOLO-World/image/ 'person,dog,machine,police' --topk 100 --threshold 0.005 --output-dir demo_outputs`
`
I consistently receive this error:
```
 zip(detections.class_id, detections.confidence)
AttributeError: 'NoneType' object has no attribute 'class_id'
```

**Comment by wondervictor** [comment]
Hi @Limbicnation, the `image_demo` does not support visualizations of segmentation masks now. We will update the demo soon

**Comment by TRMetaGroup** [comment]
@wondervictor  I encounter the same issue, the issue is "Loads checkpoint by local backend from path: yolow-v8_l_clipv2_frozen_t2iv2_bn_o365_goldg_pretrain.pth
03/05 15:41:13 - mmengine - INFO - Load checkpoint from yolow-v8_l_clipv2_frozen_t2iv2_bn_o365_goldg_pretrain.pth
[                                                  ] 0/1, elapsed: 0s, ETA:F:\anaconda\envs\yolo\lib\site-packages\torch\functional.py:507: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3550.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "Y:\Deep_learning_Pytorch\Object_Detection\YOLO-World\image_demo.py", line 186, in <module>
    inference_detector(runner,
  File "Y:\Deep_learning_Pytorch\Object_Detection\YOLO-World\image_demo.py", line 95, in inference_detector
    zip(detections.class_id, detections.confidence)
AttributeError: 'NoneType' object has no attribute 'class_id'". I am waiting for your response, thank you for this wonderful work!

**Comment by limchr** [comment]
I've written a little workaround regarding this issue where I am using my own minimalistic function for drawing bounding boxes. Just replace the 'inference_detector' function with:

```python
import math
def draw_bbox(image, bboxes, colors=None, labels=None, border_width=None, font_scale=0.5):
    image_h, image_w, _ = image.shape

    if colors is None:
        colors = [[255, 0, 0]] * len(bboxes)
    if labels is None:
        labels = [None] * len(bboxes)
    if border_width is None:
        border_width = math.ceil((image_h + image_w) / 500)

    # coords is list of x y w h
    for coords, col, label in zip(bboxes, colors, labels):
        # c1 is upper left corner, c2 is bottom right corner
        c1, c2 = [coords[0], coords[1]], [coords[0] + coords[2], coords[1] + coords[3]]
        cv2.rectangle(image, tuple(c1), tuple(c2), col, border_width)

        if not label is None:
            t_size = cv2.getTextSize(label, 0, font_scale, thickness=border_width // 2)[0]
            # c3 is right x and
            c3 = [c1[0] + t_size[0], c1[1] - t_size[1] - 4]
            if c3[1] < 0: # if text is outside image (top side)
                amount = -c3[1]
                c3[1] += amount
                c1[1] += amount
            if c3[0] > image.shape[1]:
                amount = c3[0] - image.shape[1]
                c3[0] -= amount
                c1[0] -= amount
            cv2.rectangle(image, tuple(c1), tuple(c3), col, -1)
            cv2.putText(image, label, (c1[0], c1[1] - 2), cv2.FONT_HERSHEY_SIMPLEX, font_scale, (1,1,1),
                        border_width // 2, lineType=cv2.LINE_AA)
    return image

def inference_detector(runner,
                       image_path,
                       texts,
                       max_dets,
                       score_thr,
                       output_dir,
                       use_amp=False,
                       show=False,
                       annotation=False):
    data_info = dict(img_id=0, img_path=image_path, texts=texts)
    data_info = runner.pipeline(data_info)
    data_batch = dict(inputs=data_info['inputs'].unsqueeze(0),
                      data_samples=[data_info['data_samples']])

    with autocast(enabled=use_amp), torch.no_grad():
        output = runner.model.test_step(data_batch)[0]
        pred_instances = output.pred_instances
        pred_instances = pred_instances[
            pred_instances.scores.float() > score_thr]
    if len(pred_instances.scores) > max_dets:
        indices = pred_instances.scores.float().topk(max_dets)[1]
        pred_instances = pred_instances[indices]

    pred_instances = pred_instances.cpu().numpy()
    detections = None  # Define detections object

    converted_bb = []
    bb_labels = []
    for bb, li, ss in zip(pred_instances.bboxes, pred_instances.labels, pred_instances.scores):
        new_bb = [int(bb[0]), int(bb[1]), int(bb[2]-bb[0]), int(bb[3]-bb[1])]
        converted_bb.append(new_bb)
        bb_labels.append('%s (%.2f)' % (texts[li][0], ss))

    image = cv2.imread(image_path)
    anno_image = image.copy()

    anno_image = draw_bbox(anno_image, converted_bb, labels=bb_labels, font_scale=2.)

    cv2.imwrite(osp.join(output_dir, osp.basename(image_path)), anno_image)
    if show:
        cv2.imshow('Image', anno_image)  # Provide window name
        k = cv2.waitKey(0)
        if k == 27:
            # wait for ESC key to exit
            cv2.destroyAllWindows()

```

Hope that helps anyone.

**Comment by KDgggg** [comment]
> Hi @Limbicnation, the `image_demo` does not support visualizations of segmentation masks now. We will update the demo soon

那这样的话就好像没法运行image_demo，我也是遇到这种情况

**Comment by Limbicnation** [comment]
> I've written a little workaround regarding this issue where I am using my own minimalistic function for drawing bounding boxes. Just replace the 'inference_detector' function with:
> 
> ```python
> import math
> def draw_bbox(image, bboxes, colors=None, labels=None, border_width=None, font_scale=0.5):
>     image_h, image_w, _ = image.shape
> 
>     if colors is None:
>         colors = [[255, 0, 0]] * len(bboxes)
>     if labels is None:
>         labels = [None] * len(bboxes)
>     if border_width is None:
>         border_width = math.ceil((image_h + image_w) / 500)
> 
>     # coords is list of x y w h
>     for coords, col, label in zip(bboxes, colors, labels):
>         # c1 is upper left corner, c2 is bottom right corner
>         c1, c2 = [coords[0], coords[1]], [coords[0] + coords[2], coords[1] + coords[3]]
>         cv2.rectangle(image, tuple(c1), tuple(c2), col, border_width)
> 
>         if not label is None:
>             t_size = cv2.getTextSize(label, 0, font_scale, thickness=border_width // 2)[0]
>             # c3 is right x and
>             c3 = [c1[0] + t_size[0], c1[1] - t_size[1] - 4]
>             if c3[1] < 0: # if text is outside image (top side)
>                 amount = -c3[1]
>                 c3[1] += amount
>                 c1[1] += amount
>             if c3[0] > image.shape[1]:
>                 amount = c3[0] - image.shape[1]
>                 c3[0] -= amount
>                 c1[0] -= amount
>             cv2.rectangle(image, tuple(c1), tuple(c3), col, -1)
>             cv2.putText(image, label, (c1[0], c1[1] - 2), cv2.FONT_HERSHEY_SIMPLEX, font_scale, (1,1,1),
>                         border_width // 2, lineType=cv2.LINE_AA)
>     return image
> 
> def inference_detector(runner,
>                        image_path,
>                        texts,
>                        max_dets,
>                        score_thr,
>                        output_dir,
>                        use_amp=False,
>                        show=False,
>                        annotation=False):
>     data_info = dict(img_id=0, img_path=image_path, texts=texts)
>     data_info = runner.pipeline(data_info)
>     data_batch = dict(inputs=data_info['inputs'].unsqueeze(0),
>                       data_samples=[data_info['data_samples']])
> 
>     with autocast(enabled=use_amp), torch.no_grad():
>         output = runner.model.test_step(data_batch)[0]
>         pred_instances = output.pred_instances
>         pred_instances = pred_instances[
>             pred_instances.scores.float() > score_thr]
>     if len(pred_instances.scores) > max_dets:
>         indices = pred_instances.scores.float().topk(max_dets)[1]
>         pred_instances = pred_instances[indices]
> 
>     pred_instances = pred_instances.cpu().numpy()
>     detections = None  # Define detections object
> 
>     converted_bb = []
>     bb_labels = []
>     for bb, li, ss in zip(pred_instances.bboxes, pred_instances.labels, pred_instances.scores):
>         new_bb = [int(bb[0]), int(bb[1]), int(bb[2]-bb[0]), int(bb[3]-bb[1])]
>         converted_bb.append(new_bb)
>         bb_labels.append('%s (%.2f)' % (texts[li][0], ss))
> 
>     image = cv2.imread(image_path)
>     anno_image = image.copy()
> 
>     anno_image = draw_bbox(anno_image, converted_bb, labels=bb_labels, font_scale=2.)
> 
>     cv2.imwrite(osp.join(output_dir, osp.basename(image_path)), anno_image)
>     if show:
>         cv2.imshow('Image', anno_image)  # Provide window name
>         k = cv2.waitKey(0)
>         if k == 27:
>             # wait for ESC key to exit
>             cv2.destroyAllWindows()
> ```
> 
> Hope that helps anyone.

Thank you! I've attempted to run this code, but the output folder is still empty. Could you offer any advice on the command or share the full code?

`# Copyright (c) Tencent Inc. All rights reserved.
import os
import cv2
import argparse
import os.path as osp
import torch
import math
from mmengine.config import Config, DictAction
from mmengine.runner import Runner
from mmengine.runner.amp import autocast
from mmengine.dataset import Compose
from mmengine.utils import ProgressBar
from mmyolo.registry import RUNNERS

BOUNDING_BOX_ANNOTATOR = None  # Placeholder, not used in modified version
LABEL_ANNOTATOR = None  # Placeholder, not used in modified version

def parse_args():
    parser = argparse.ArgumentParser(description='YOLO-World Demo')
    # arguments setup
    args = parser.parse_args()
    return args

def draw_bbox(image, bboxes, colors=None, labels=None, border_width=None, font_scale=0.5):
    # Draw bounding boxes and labels on the image
    return image

import math
def draw_bbox(image, bboxes, colors=None, labels=None, border_width=None, font_scale=0.5):
    image_h, image_w, _ = image.shape

    if colors is None:
        colors = [[255, 0, 0]] * len(bboxes)
    if labels is None:
        labels = [None] * len(bboxes)
    if border_width is None:
        border_width = math.ceil((image_h + image_w) / 500)

    # coords is list of x y w h
    for coords, col, label in zip(bboxes, colors, labels):
        # c1 is upper left corner, c2 is bottom right corner
        c1, c2 = [coords[0], coords[1]], [coords[0] + coords[2], coords[1] + coords[3]]
        cv2.rectangle(image, tuple(c1), tuple(c2), col, border_width)

        if not label is None:
            t_size = cv2.getTextSize(label, 0, font_scale, thickness=border_width // 2)[0]
            # c3 is right x and
            c3 = [c1[0] + t_size[0], c1[1] - t_size[1] - 4]
            if c3[1] < 0: # if text is outside image (top side)
                amount = -c3[1]
                c3[1] += amount
                c1[1] += amount
            if c3[0] > image.shape[1]:
                amount = c3[0] - image.shape[1]
                c3[0] -= amount
                c1[0] -= amount
            cv2.rectangle(image, tuple(c1), tuple(c3), col, -1)
            cv2.putText(image, label, (c1[0], c1[1] - 2), cv2.FONT_HERSHEY_SIMPLEX, font_scale, (1,1,1),
                        border_width // 2, lineType=cv2.LINE_AA)
    return image

def inference_detector(runner,
                       image_path,
                       texts,
                       max_dets,
                       score_thr,
                       output_dir,
                       use_amp=False,
                       show=False,
                       annotation=False):
    data_info = dict(img_id=0, img_path=image_path, texts=texts)
    data_info = runner.pipeline(data_info)
    data_batch = dict(inputs=data_info['inputs'].unsqueeze(0),
                      data_samples=[data_info['data_samples']])

    with autocast(enabled=use_amp), torch.no_grad():
        output = runner.model.test_step(data_batch)[0]
        pred_instances = output.pred_instances
        pred_instances = pred_instances[
            pred_instances.scores.float() > score_thr]
    if len(pred_instances.scores) > max_dets:
        indices = pred_instances.scores.float().topk(max_dets)[1]
        pred_instances = pred_instances[indices]

    pred_instances = pred_instances.cpu().numpy()
    detections = None  # Define detections object

    converted_bb = []
    bb_labels = []
    for bb, li, ss in zip(pred_instances.bboxes, pred_instances.labels, pred_instances.scores):
        new_bb = [int(bb[0]), int(bb[1]), int(bb[2]-bb[0]), int(bb[3]-bb[1])]
        converted_bb.append(new_bb)
        bb_labels.append('%s (%.2f)' % (texts[li][0], ss))

    image = cv2.imread(image_path)
    anno_image = image.copy()

    anno_image = draw_bbox(anno_image, converted_bb, labels=bb_labels, font_scale=2.)

    cv2.imwrite(osp.join(output_dir, osp.basename(image_path)), anno_image)
    if show:
        cv2.imshow('Image', anno_image)  # Provide window name
        k = cv2.waitKey(0)
        if k == 27:
            # wait for ESC key to exit
            cv2.destroyAllWindows()
`

**Comment by wondervictor** [comment]
Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
