### ISSUE TITLE
inference

### ISSUE THREAD

**Issue by KDgggg** [AILab-CVC/YOLO-World#96]
请问支持不输入文本，直接输入图像给出检测结果吗

**Comment by wondervictor** [comment]
@KDgggg，您好，这个是支持的，您可以提前定义好自己需要的vocabulary，然后就可以只用输入图像了，这一步目前需要修改code或者直接使用部署的流程吧。

**Comment by wondervictor** [comment]
This issue will be closed since there is no further update related to the main topic. Thanks for your interest.  If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
