### ISSUE TITLE
GPU requirements for fine-tuning

### ISSUE THREAD

**Issue by SarahWSY** [AILab-CVC/YOLO-World#99]
Hi, would it be possible to fine-tune the YOLO-World L with 4 RTX A5000(24GB VRAM)? And roughly how long will each epoch be? 

Thanks in advance!

**Comment by wondervictor** [comment]
Hi @SarahWSY, 4 GPUs are enough to fine-tune YOLO-World-L. The fine-tuning process of YOLO-World-L on COCO takes nearly 12 hours (80 epochs).

**Comment by wondervictor** [comment]
Thanks for your interest. If you have any questions about YOLO-World in the future, you're welcome to open a new issue.
